<?php

namespace Database\Seeders;

use App\Models\BasicSettings\Bank;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;


class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            [
                'id' => 1,
                'name' => 'Bangladesh Bank',
                'bn_name' => 'বাংলাদেশ ব্যাংক',
                'slug' => Str::slug('Bangladesh Bank', '-'),
                'url'=> 'https://www.bb.org.bd/',
                'address' => 'Bangladesh Bank, Motijheel, Dhaka',
                'status' => true,
                'description' => 'Central Bank'
            ],
            [
                'id' => 2,
                'name' => 'Sonali Bank',
                'bn_name' => 'সোনালী ব্যাংক',
                'slug' => Str::slug('Sonali Bank', '-'),
                'url'=> 'https://www.sonalibank.com.bd/',
                'address' => 'Sonali Bank ; Corporate Address, 35-42, 44 Motijheel Commercial Area, Dhaka 1000',
                'status' => true, 
                'description' => 'State-owned Commercial'
            ],
            [
                'id' => 3, 
                'name' => 'Agrani Bank',
                'bn_name' => 'অগ্রণী ব্যাংক',
                'slug' => Str::slug('Agrani Bank', '-'),
                'url'=> 'https://www.agranibank.org/',
                'address' => 'Head office: 9/D Dilkusha Commercial Area, Dhaka - 1000',
                'status' => true, 
                'description' => 'State-owned Commercial'
            ],
            [
                'id' => 4,
                'name' => 'Rupali Bank', 
                'bn_name' => 'রূপালী ব্যাংক',
                'slug' => Str::slug('Rupali Bank', '-'),
                'url'=> 'https://rupalibank.com.bd/',
                'address' => ' Rupali Bhaban, 34 Dilkusha Commercial Area, Dhaka 1000, Bangladesh',
                'status' => true, 
                'description' => 'State-owned Commercial'
            ],
            [
                'id' => 5,
                'name' => 'Janata Bank', 
                'description' => 'State-owned Commercial',
                'bn_name' => 'জনতা ব্যাংক লিমিটেড',
                'slug' => Str::slug('Janata Bank', '-'),
                'url'=> 'https://www.jb.com.bd/',
                'address' => 'Janata Bank Limited, 110, Motijheel Commercial Area Dhaka-1000, Bangladesh',
                'status' => true, 
            ],
            [
                'id' => 6,
                'name' => 'BRAC Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'ব্র্যাক ব্যাংক',
                'slug' => Str::slug('BRAC Bank Limited', '-'),
                'url'=> 'https://www.bracbank.com/',
                'address' => 'BRAC Bank Limited Anik Tower 220/B, Tejgaon Gulshan Link Road Tejgaon, Dhaka, Dhaka, Bangladesh',
                'status' => true, 
            ],
            [
                'id' => 7,
                'name' => 'Dutch Bangla Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'ডাচ-বাংলা ব্যাংক',
                'slug' => Str::slug('Dutch Bangla Bank Limited', '-'),
                'url'=> 'https://www.dutchbanglabank.com/',
                'address' => '47 Motijheel Commercial Area Dhaka-1000, Bangladesh',
                'status' => true, 
            ],
            [
                'id' => 8,
                'name' => 'Eastern Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'ইস্টার্ণ ব্যাংক লিমিটেড',
                'slug' => Str::slug('Eastern Bank Limited', '-'),
                'url'=> 'https://www.ebl.com.bd/',
                'address' => 'Eastern Bank Ltd. 100 Gulshan Avenue Dhaka-1212',
                'status' => true, 
            ],
            [
                'id' => 9,
                'name' => 'United Commercial Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'ইউনাইডেট কমার্শিয়াল ব্যাংক লিমিটেড',
                'slug' => Str::slug('United Commercial Bank Limited', '-'),
                'url'=> 'https://www.ucb.com.bd/',
                'address' => '',
                'status' => true
            ],
            [
                'id' => 10,
                'name' => 'Mutual Trust Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'মিউচুয়াল ট্রাস্ট ব্যাংক লিমিটেড',
                'slug' => Str::slug('Mutual Trust Bank Limited', '-'),
                'url'=> 'https://www.mutualtrustbank.com/',
                'address' => 'MTB Centre 26 Gulshan Avenue, Dhaka 1212, Banglades',
                'status' => true, 
            ],
            [
                'id' => 11,
                'name' => 'Dhaka Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'ঢাকা ব্যাংক লিমিটেড',
                'slug' => Str::slug('Dhaka Bank Limited', '-'),
                'url'=> 'https://dhakabankltd.com/',
                'address' => '71, Purana Paltan Lane, Dhaka-1000',
                'status' => true, 
            ],
            [
                'id' => 12,
                'name' => 'Islami Bank Bangladesh Ltd', 
                'description' => 'Private Commercial',
                'bn_name' => 'ইসলামী ব্যাংক বাংলাদেশ লিমিটেড',
                'slug' => Str::slug('Islami Bank Bangladesh Ltd', '-'),
                'url'=> 'https://www.islamibankbd.com/',
                'address' => 'Islami Bank Tower. 40, Dilkusha C/A Dhaka - 1000, Bangladesh',
                'status' => true, 
            ],
            [
                'id' => 13,
                'name' => 'Uttara Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'উত্তরা ব্যাংক লিমিটেড',
                'slug' => Str::slug('Uttara Bank Limited', '-'),
                'url'=> 'https://www.uttarabank-bd.com/',
                'address' => 'House-34 Gareeb-e-Nawaz Ave, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 14,
                'name' => 'Pubali Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'পূবালী ব্যাংক লিমিটেড',
                'slug' => Str::slug('Pubali Bank Limited', '-'),
                'url'=> 'https://www.pubalibangla.com/',
                'address' => 'Chairman Market, 93 Shahid Latif Rd, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 15,
                'name' => 'IFIC Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'আইএফ‌আইসি ব্যাংক লিমিটেড',
                'slug' => Str::slug('IFIC Bank Limited', '-'),
                'url'=> 'https://www.ificbank.com.bd/',
                'address' => 'ABC Heritage, Plot No. 2 & 4, Jashimuddin Ave, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 16,
                'name' => 'National Bank Limited',
                'description' => 'Private Commercial',
                'bn_name' => 'ন্যাশনাল ব্যাংক লিমিটেড',
                'slug' => Str::slug('National Bank Limited', '-'),
                'url'=> 'https://www.nblbd.com/',
                'address' => 'Plot No, Hossain Tower, 103 Dhaka - Mymensingh Hwy, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 17,
                'name' => 'The City Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'সিটি ব্যাংক লিমিটেড',
                'slug' => Str::slug('The City Bank Limited', '-'),
                'url'=> 'https://www.thecitybank.com/',
                'address' => 'City Bank Center 136, Gulshan Avenue, Gulshan-2 Dhaka-1212, Bangladesh',
                'status' => true, 
            ],
            [
                'id' => 18,
                'name' => 'NCC Bank Limited',
                'description' => 'Private Commercial',
                'bn_name' => 'এনসিসি ব্যাংক লিমিটেড',
                'slug' => Str::slug('NCC Bank Limited', '-'),
                'url'=> 'https://www.nccbank.com.bd/',
                'address' => ' K.C. Plaza (1st Floor), Shaheed Latif Road, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 19,
                'name' => 'Mercantile Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'মার্কেন্টাইল ব্যাংক লিমিটেড',
                'slug' => Str::slug('Mercantile Bank Limited', '-'),
                'url'=> 'https://www.mblbd.com/',
                'address' => 'RC5C+XHX, Progati Sarani Rd, Dhaka 1212',
                'status' => true, 
            ],
            [
                'id' => 20,
                'name' => 'Southeast Bank Limited',
                'description' => 'Private Commercial',
                'bn_name' => 'সাউথইস্ট ব্যাংক',
                'slug' => Str::slug('Southeast Bank Limited', '-'),
                'url'=> 'https://www.southeastbank.com.bd/',
                'address' => 'Faisal Mansion, Shah Kabir Mazar Rd, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 21,
                'name' => 'Prime Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'প্রাইম ব্যাংক লিমিটেড',
                'slug' => Str::slug('Prime Bank Limited', '-'),
                'url'=> 'https://www.primebank.com.bd/',
                'address' => ' Sena Kalyan Commercial Complex (1st Floor), Plot # 9, Block #F,, Dhaka - Mymensingh Hwy, Tongi',
                'status' => true, 
            ],
            [
                'id' => 22,
                'name' => 'Social Islami Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'সোশ্যাল ইসলামী ব্যাংক লিমিটেড',
                'slug' => Str::slug('Social Islami Bank Limited', '-'),
                'url'=> 'https://www.siblbd.com/',
                'address' => 'Social Islami Bank Limited City Center, Level: 19-23, 28 and 29 90/1, Motijheel Commercial Area Dhaka-1000. ',
                'status' => true, 
            ],
            [
                'id' => 23,
                'name' => 'Standard Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'স্ট্যান্ডার্ড ব্যাংক লিমিটেড',
                'slug' => Str::slug('Standard Bank Limited', '-'),
                'url'=> 'https://www.standardbankbd.com/',
                'address' => '122-124 Motijheel C/A, Dhaka-1000, Bangladesh',
                'status' => true, 
            ],
            [
                'id' => 24,
                'name' => 'Al-Arafah Islami Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'আল-আরাফাহ ইসলামী ব্যাংক লিমিটেড',
                'slug' => Str::slug('Al-Arafah Islami Bank Limited', '-'),
                'url'=> 'https://www.aibl.com.bd/',
                'address' => 'Head Office, Al-Arafah Tower, 63, Purana Paltan, Dhaka-1000.',
                'status' => true, 
            ],
            [
                'id' => 25,
                'name' => 'One Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'ওয়ান ব্যাংক লিমিটেড',
                'slug' => Str::slug('One Bank Limited', '-'),
                'url'=> 'https://www.onebank.com.bd/',
                'address' => 'House-14 Road-14/B, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 26,
                'name' => 'Exim Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'এক্সিম ব্যাংক (বাংলাদেশ)',
                'slug' => Str::slug('Exim Bank Limited', '-'),
                'url'=> 'https://www.eximbankbd.com/',
                'address' => 'Sharif Mansion 56‑57,Motijhil C/A, Dhaka',
                'status' => true, 
            ],
            [
                'id' => 27,
                'name' => 'First Security Islami Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'ফার্স্ট সিকিউরিটি ইসলামী ব্যাংক লিমিটেড',
                'slug' => Str::slug('First Security Islami Bank Limited', '-'),
                'url'=> 'https://fsiblbd.com/',
                'address' => '65, MuktiJodda Road, Panna Plaza, Ajampur super Market, Dokkhin Khan, 1230',
                'status' => true, 
            ],
            [
                'id' => 28,
                'name' => 'Bank Asia Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'ব্যাংক এশিয়া লিমিটেড',
                'slug' => Str::slug('Bank Asia Limited', '-'),
                'url'=> 'http://www.bankasia-bd.com/',
                'address' => ' Bank Asia Tower,32 & 34, Kazi Nazrul Islam Avenue, Karwan Bazar, Dhaka',
                'status' => true, 
            ],
            [
                'id' => 29,
                'name' => 'The Premier Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'প্রিমিয়ার ব্যাংক লিমিটেড',
                'slug' => Str::slug('The Premier Bank Limited', '-'),
                'url'=> 'https://premierbankltd.com/',
                'address' => 'Iqbal Centre, 42 Kemal Ataturk Avenue, Banani, Dhaka, Bangladesh',
                'status' => true, 
            ],
            [
                'id' => 30,
                'name' => 'Bangladesh Commerce Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'বাংলাদেশ কমার্স ব্যাংক লিমিটেড',
                'slug' => Str::slug('Bangladesh Commerce Bank Limited', '-'),
                'url'=> 'https://bcblbd.com/',
                'address' => ' RC8C+9G5, Pragati Ave, Dhaka',
                'status' => true, 
            ],
            [
                'id' => 31,
                'name' => 'Trust Bank Limited',
                'description' => 'Private Commercial',
                'bn_name' => 'ট্রাস্ট ব্যাংক লিমিটেড',
                'slug' => Str::slug('Trust Bank Limited', '-'),
                'url'=> 'https://www.tblbd.com/',
                'address' => 'Holding-111/A (Ground & 1st floor, Rd 7, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 32,
                'name' => 'Jamuna Bank Limited',
                'description' => 'Private Commercial',
                'bn_name' => 'যমুনা ব্যাংক লিমিটেড',
                'slug' => Str::slug('Jamuna Bank Limited', '-'),
                'url'=> 'https://jamunabankbd.com/',
                'address' => 'Jamuna Bank Tower, Plot# 14, Bir Uttam A. K. Khandaker Road, Block# C, Gulshan-1, Dhaka, Bangladesh',
                'status' => true, 
            ],
            [
                'id' => 33,
                'name' => 'Shahjalal Islami Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'শাহ্‌জালাল ইসলামী ব্যাংক লিমিটেড',
                'slug' => Str::slug('Shahjalal Islami Bank Limited', '-'),
                'url'=> 'https://sjiblbd.com/',
                'address' => 'SHAHJALAL ISLAMI BANK LIMITED, NEW ESKATON ROAD, 122-123, ESKATON FANTASIA, DHAKA',
                'status' => true, 
            ],
            [
                'id' => 34,
                'name' => 'ICB Islamic Bank',
                'description' => 'Private Commercial',
                'bn_name' => 'আইসিবি ইসলামিক ব্যাংক লিমিটেড',
                'slug' => Str::slug('ICB Islamic Bank', '-'),
                'url'=> 'https://icbislamic-bd.com/',
                'address' => '',
                'status' => true, 
            ],
            [
                'id' => 35,
                'name' => 'AB Bank', 
                'description' => 'Private Commercial',
                'bn_name' => 'এবি ব্যাংক লিমিটেড',
                'slug' => Str::slug('AB Bank', '-'),
                'url'=> 'https://abbl.com/',
                'address' => 'Asset Brookhaven, Road-14/D, Dhaka 1230',
                'status' => true, 
            ],
            [
                'id' => 36,
                'name' => 'Jubilee Bank Limited', 
                'description' => 'Private Commercial',
                'bn_name' => 'জুবিলী ব্যাংক',
                'slug' => Str::slug('Jubilee Bank Limited', '-'),
                'url'=> '',
                'address' => 'Haque Tower(1st Floor) 610/11,Jubilee Road, Chattogram',
                'status' => true, 
            ],
            [
                'id' => 37,
                'name' => 'Karmasangsthan Bank',
                'description' => 'Specialized Development',
                'bn_name' => 'কর্মসংস্থান ব্যাংক',
                'slug' => Str::slug('Karmasangsthan Bank', '-'),
                'url'=> 'http://www.kb.gov.bd/',
                'address' => 'Karmasangsthan Bank, Narayangonj Branch, 152, B.B Road, Alhaz Benu Tower, (3rd Floor), Narayangonj.',
                'status' => true, 
            ],
            [
                'id' => 38,
                'name' => 'Bangladesh Krishi Bank',
                'description' => 'Specialized Development',
                'bn_name' => 'বাংলাদেশ কৃষি ব্যাংক',
                'slug' => Str::slug('Bangladesh Krishi Bank', '-'),
                'url'=> 'https://www.krishibank.org.bd/',
                'address' => 'Bangladesh Krishi Bank,Krishi Bank Bhaban, 83-85 Motijheel Commercial Area, –1000, Bangladesh',
                'status' => true,
            ],
            [
                'id' => 39,
                'name' => 'Progoti Bank', 
                'description' => 'Specialized Development',
                'bn_name' => 'প্রগতি',
                'slug' => Str::slug('Progoti Bank', '-'),
                'url'=> 'https://abbl.com/',
                'address' => null,
                'status' => true, 
            ],
            [
                'id' => 40,
                'name' => 'Rajshahi Krishi Unnayan Bank',
                'description' => 'Specialized Development',
                'bn_name' => 'রাজশাহী কৃষি উন্নয়ন ব্যাংক',
                'slug' => Str::slug('Rajshahi Krishi Unnayan Bank', '-'),
                'url'=> 'রাজশাহী কৃষি উন্নয়ন ব্যাংক',
                'address' => '',
                'status' => true, 
            ],
            [
                'id' => 41,
                'name' => 'Bangladesh Development Bank Ltd',
                'description' => 'Specialized Development',
                'bn_name' => 'বাংলাদেশ ডেভেলপমেন্ট ব্যাংক লিমিটেড',
                'slug' => Str::slug('Bangladesh Development Bank Ltd', '-'),
                'url'=> 'https://bdbl.com.bd/',
                'address' => null,
                'status' => true, 
            ],
            [
                'id' => 42,
                'name' => 'Bangladesh Somobay Bank Limited',
                'description' => 'Specialized Development',
                'bn_name' => 'বাংলাদেশ সমবায় ব্যাংক লিমিটেড',
                'slug' => Str::slug('Bangladesh Somobay Bank Limited', '-'),
                'url'=> 'http://www.bsbl.org.bd/',
                'address' => '',
                'status' => true, 
            ],
            [
                'id' => 43,
                'name' => 'Grameen Bank', 
                'description' => 'Specialized Development',
                'bn_name' => 'গ্রামীণ ব্যাংক',
                'slug' => Str::slug('Grameen Bank', '-'),
                'url'=> 'https://grameenbank.org/',
                'address' => ' RCVV+CP5, Unnamed Road, Dhaka 1229',
                'status' => true, 
            ],
            [
                'id' => 44,
                'name' => 'BASIC Bank Limited',
                'description' => 'Specialized Development',
                'bn_name' => 'বেসিক ব্যাংক লিমিটেড',
                'slug' => Str::slug('BASIC Bank Limited', '-'),
                'url'=> 'https://www.basicbanklimited.com/Green_Banking.php',
                'address' => '',
                'status' => true, 
            ],
            [
                'id' => 45,
                'name' => 'Ansar VDP Unnyan Bank', 
                'description' => 'Specialized Development',
                'bn_name' => 'আনসার-ভিডিপি উন্নয়ন ব্যাংক',
                'slug' => Str::slug('Ansar VDP Unnyan Bank', '-'),
                'url'=> 'https://ansarvdpbank.portal.gov.bd/',
                'address' => '14, Outer Circulr, Rajarbag, Dhaka-1217',
                'status' => true, 
            ],
            [
                'id' => 46,
                'name' => 'The Dhaka Mercantile Co-operative Bank Limited(DMCBL)', 
                'description' => 'Specialized Development',
                'bn_name' => 'দি ঢাকা মার্কেন্টাইল কো-অপারেটিভ ব্যাংক লিমিটেড',
                'slug' => Str::slug('The Dhaka Mercantile Co-operative Bank Limited(DMCBL)', '-'),
                'url'=> 'https://dmcbl.com/',
                'address' => '19, Indira Road, Farmgate, Tejgaon, Dhaka-1215',
                'status' => true, 
            ],
            [
                'id' => 47,
                'name' => 'HSBC', 
                'description' => 'Foreign Commercial',
                'bn_name' => 'এইচএসবিসি',
                'slug' => Str::slug('HSBC', '-'),
                'url'=> 'https://www.hsbc.com.bd',
                'address' => null,
                'status' => true, 
            ],
            [
                'id' => 48,
                'name' => 'Standard Chartered Bank',
                'description' => 'Foreign Commercial',
                'bn_name' => 'স্ট্যান্ডার্ড চার্টার্ড বাংলাদেশ',
                'slug' => Str::slug('Standard Chartered Bank', '-'),
                'url'=> 'https://www.sc.com/bd/',
                'address' => ' Plot: 1, Update Tower, Shahajalal Ave, Dhaka 1230',
                'status' => true, 
            ],
            
            [
                'id' => 49,
                'name' => 'WooriBank',
                'description' => 'Foreign Commercial',
                'bn_name' => 'উরি ব্যাংক',
                'slug' => Str::slug('WooriBank', '-'),
                'url'=> 'https://go.wooribank.com/bd/ib/main/IbMain.do',
                'address' => 'uvastu Imam Square, 65 Gulshan Avenue, Dhaka',
                'status' => true, 
            ],
            [
                'id' => 50,
                'name' => 'Bank Alfalah',
                'description' => 'Foreign Commercial',
                'bn_name' => 'ব্যাংক আলফালাহ',
                'slug' => Str::slug('Bank Alfalah', '-'),
                'url'=> 'https://www.bankalfalah.com/bd/',
                'address' => '168 Gulshan Avenue, Dhaka 1212, Bangladesh',
                'status' => true, 
            ],
        ];
        Bank::insert($banks);
    }
}
