<?php

namespace Database\Seeders;

use App\Models\BasicSettings\Mouza;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MouzaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Mouza::truncate();
        $data = [

            // Bheramra-201 RS-4
                    ['jl_no' => 1, 'thana_id' => 201, 'name' => 'Rayta', 'bn_name' => 'রায়টা', 'survey_id' => 4],
                    ['jl_no' => 2, 'thana_id' => 201, 'name' => 'Fayjullapur', 'bn_name' => 'ফয়জুল্যাপুর', 'survey_id' => 4],
                    ['jl_no' => 3, 'thana_id' => 201, 'name' => 'Horipur', 'bn_name' => 'হরিপুর', 'survey_id' => 4],
                    ['jl_no' => 4, 'thana_id' => 201, 'name' => 'Meghnapara', 'bn_name' => 'মেঘনাপাড়া', 'survey_id' => 4],
                    ['jl_no' => 5, 'thana_id' => 201, 'name' => 'Arkandi', 'bn_name' => 'আড়কান্দি', 'survey_id' => 4],
                    ['jl_no' => 6, 'thana_id' => 201, 'name' => 'Madhobpur', 'bn_name' => 'মাধবপুর', 'survey_id' => 4],
                    ['jl_no' => 7, 'thana_id' => 201, 'name' => 'Bashudebpur', 'bn_name' => 'বাসুদেবপুর', 'survey_id' => 4],
                    ['jl_no' => 8, 'thana_id' => 201, 'name' => 'Bahadurpur', 'bn_name' => 'বাহাদুরপুর', 'survey_id' => 4],
                    ['jl_no' => 9, 'thana_id' => 201, 'name' => 'Golapnogor', 'bn_name' => 'গোলাপনগর', 'survey_id' => 4],
                    ['jl_no' => 10, 'thana_id' => 201, 'name' => 'Chor Golapnogor', 'bn_name' => 'চর গোলাপনগর', 'survey_id' => 4],
                    ['jl_no' => 11, 'thana_id' => 201, 'name' => 'Arjisara', 'bn_name' => 'আরজিসারা', 'survey_id' => 4],
                    ['jl_no' => 12, 'thana_id' => 201, 'name' => 'Chor Ruppur', 'bn_name' => 'চর রূপপুর', 'survey_id' => 4],
                    ['jl_no' => 13, 'thana_id' => 201, 'name' => 'Chor Mokarimpur', 'bn_name' => 'চর মোকারিমপুর', 'survey_id' => 4],
                    ['jl_no' => 14, 'thana_id' => 201, 'name' => 'Mokarimpur', 'bn_name' => 'মোকারিমপুর', 'survey_id' => 4],
                    ['jl_no' => 15, 'thana_id' => 201, 'name' => 'Fakirabad', 'bn_name' => 'ফকিরাবাদ', 'survey_id' => 4],
                    ['jl_no' => 16, 'thana_id' => 201, 'name' => 'Jhikri Porankhali', 'bn_name' => 'ঝিকড়ী পরান খালী', 'survey_id' => 4],
                    ['jl_no' => 17, 'thana_id' => 201, 'name' => 'Dawlatpur', 'bn_name' => 'দৌলতপুর', 'survey_id' => 4],
                    ['jl_no' => 18, 'thana_id' => 201, 'name' => 'Thakur Dawlatpur', 'bn_name' => 'ঠাকুর দৌলতপুর', 'survey_id' => 4],
                    ['jl_no' => 19, 'thana_id' => 201, 'name' => 'Juniadaha', 'bn_name' => 'জুনিয়াদহ', 'survey_id' => 4],
                    ['jl_no' => 20, 'thana_id' => 201, 'name' => 'Mirzapur', 'bn_name' => 'মির্জ্জাপুর', 'survey_id' => 4],
                    ['jl_no' => 21, 'thana_id' => 201, 'name' => 'Dolua', 'bn_name' => 'দলুয়া', 'survey_id' => 4],
                    ['jl_no' => 22, 'thana_id' => 201, 'name' => 'Gobindopur', 'bn_name' => 'গোবিন্দপুর', 'survey_id' => 4],
                    ['jl_no' => 23, 'thana_id' => 201, 'name' => 'Nolua', 'bn_name' => 'নলুয়া', 'survey_id' => 4],
                    ['jl_no' => 24, 'thana_id' => 201, 'name' => 'Patuakandi', 'bn_name' => 'পাটুয়াকান্দি', 'survey_id' => 4],
                    ['jl_no' => 25, 'thana_id' => 201, 'name' => 'Jogossor', 'bn_name' => 'যগশ্বর', 'survey_id' => 4],
                    ['jl_no' => 26, 'thana_id' => 201, 'name' => 'Poschima', 'bn_name' => 'পশ্চিমা', 'survey_id' => 4],
                    ['jl_no' => 27, 'thana_id' => 201, 'name' => 'Nobogonga', 'bn_name' => 'নবগঙ্গা', 'survey_id' => 4],
                    ['jl_no' => 28, 'thana_id' => 201, 'name' => 'Kazihata', 'bn_name' => 'কাজীহাটি', 'survey_id' => 4],
                    ['jl_no' => 29, 'thana_id' => 201, 'name' => 'Dharampur', 'bn_name' => 'ধরমপুর', 'survey_id' => 4],
                    ['jl_no' => 30, 'thana_id' => 201, 'name' => 'Satbaria', 'bn_name' => 'সাতবাড়িয়া', 'survey_id' => 4],
                    ['jl_no' => 31, 'thana_id' => 201, 'name' => 'Nitarpol', 'bn_name' => 'নিতারপোল', 'survey_id' => 4],
                    ['jl_no' => 32, 'thana_id' => 201, 'name' => 'Kodalipara', 'bn_name' => 'কোদালীয়াপাড়া', 'survey_id' => 4],
                    ['jl_no' => 33, 'thana_id' => 201, 'name' => 'Himir Dia', 'bn_name' => 'হিড়িম দিয়া', 'survey_id' => 4],
                    ['jl_no' => 34, 'thana_id' => 201, 'name' => 'Chandipur', 'bn_name' => 'চন্ডীপুর', 'survey_id' => 4],
                    ['jl_no' => 35, 'thana_id' => 201, 'name' => 'Baradi', 'bn_name' => 'বাড়াদী', 'survey_id' => 4],
                    ['jl_no' => 36, 'thana_id' => 201, 'name' => 'Chadgram', 'bn_name' => 'চাঁদ গ্রাম', 'survey_id' => 4],
                    ['jl_no' => 37, 'thana_id' => 201, 'name' => 'Bamanpara', 'bn_name' => 'বামনপাড়া', 'survey_id' => 4],
                    ['jl_no' => 38, 'thana_id' => 201, 'name' => 'Bheramara', 'bn_name' => 'ভেড়ামারা', 'survey_id' => 4],
                    ['jl_no' => 39, 'thana_id' => 201, 'name' => 'Nawdapara', 'bn_name' => 'নওদাপাড়া', 'survey_id' => 4],
                    ['jl_no' => 40, 'thana_id' => 201, 'name' => 'Chak Bheramara', 'bn_name' => 'চক ভেড়ামারা', 'survey_id' => 4],
                    ['jl_no' => 41, 'thana_id' => 201, 'name' => 'Damukdua', 'bn_name' => 'দামুকদিয়া', 'survey_id' => 4],
                    ['jl_no' => 42, 'thana_id' => 201, 'name' => 'Bahirchor Poschima', 'bn_name' => 'বাহিরচর পশ্চিম', 'survey_id' => 4],
                    ['jl_no' => 43, 'thana_id' => 201, 'name' => 'West Chor Dadapur', 'bn_name' => 'ওয়েষ্ট চর দাদাপুর', 'survey_id' => 4],
            // Bheramra-201 RS-4

            // Start::Sherpur Sadar-457 CS-1
                    ["bn_name" => "ধলা", "jl_no" => "90", "thana_id" => "457", "survey_id" => "1", "name" => "Dhola",],
                    ["bn_name" => "হোসেনপুর", "jl_no" => "85", "thana_id" => "457", "survey_id" => "1", "name" => "Hossenpur",],
                    ["bn_name" => "রামখিলা", "jl_no" => "88", "thana_id" => "457", "survey_id" => "1", "name" => "Ramkhila",],
                    ["bn_name" => "ঝাউয়েরচর", "jl_no" => "60", "thana_id" => "457", "survey_id" => "1", "name" => "Jhauyerchar",],
                    ["bn_name" => "ছাতারকান্দি", "jl_no" => "45", "thana_id" => "457", "survey_id" => "1", "name" => "Satarkandi",],
                    ["bn_name" => "চররামপুর", "jl_no" => "98", "thana_id" => "457", "survey_id" => "1", "name" => "Charrampur",],
                    ["bn_name" => "রৌহা", "jl_no" => "104", "thana_id" => "457", "survey_id" => "1", "name" => "Rouha",],
                    ["bn_name" => "বেতমারি", "jl_no" => "74", "thana_id" => "457", "survey_id" => "1", "name" => "Betmari",],
                    ["bn_name" => "চরখারচর", "jl_no" => "74", "thana_id" => "457", "survey_id" => "1", "name" => "Charkharchar",],
                    ["bn_name" => "চরবেতমারি", "jl_no" => "105", "thana_id" => "457", "survey_id" => "1", "name" => "Charbetmari",],
                    ["bn_name" => "চরবড়ইগাছি", "jl_no" => "106", "thana_id" => "457", "survey_id" => "1", "name" => "Charboroigasi",],
                    ["bn_name" => "সোলারচর", "jl_no" => "75", "thana_id" => "457", "survey_id" => "1", "name" => "Sholarchar",],
                    ["bn_name" => "সোলারচর", "jl_no" => "77", "thana_id" => "457", "survey_id" => "1", "name" => "Sholarchar",],
                    ["bn_name" => "দোছরাছনকান্দা", "jl_no" => "62", "thana_id" => "457", "survey_id" => "1", "name" => "Dosorasonkanda",],
            // End::Sherpur Sadar-457 CS-1

            // Start::Sherpur Sadar-457 CS-2
                    ["bn_name" => "সোলারচর", "jl_no" => "70", "thana_id" => "457", "survey_id" => "2", "name" => "Sholarchar",],
                    ["bn_name" => "সন্ন্যাসীরচর", "jl_no" => "85", "thana_id" => "457", "survey_id" => "2", "name" => "Sonnashirchar",],
                    ["bn_name" => "হেরুয়া", "jl_no" => "86", "thana_id" => "457", "survey_id" => 2, "name" => "Herua",],
                    ["bn_name" => "কীত্তিগঞ্জ", "jl_no" => "87", "thana_id" => "457", "survey_id" => 2, "name" => "Kirtiganj",],
                    ["bn_name" => "বৈষ্ণবনগর", "jl_no" => "88", "thana_id" => "457", "survey_id" => 2, "name" => "Boishnobnagar",],
                    ["bn_name" => "চরশেরপুর", "jl_no" => "89", "thana_id" => "457", "survey_id" => 2, "name" => "Charsherpur",],
                    ["bn_name" => "জোতকসবা", "jl_no" => "90", "thana_id" => "457", "survey_id" => 2, "name" => "Jotkoshba",],
                    ["bn_name" => "যোগনীবাগ", "jl_no" => "91", "thana_id" => "457", "survey_id" => 2, "name" => "Jognibag",],
                    ["bn_name" => "যোগনীমুড়া", "jl_no" => "92", "thana_id" => "457", "survey_id" => 2, "name" => "Jognimura",],
                    ["bn_name" => "রামচন্দ্রপুর", "jl_no" => "93", "thana_id" => "457", "survey_id" => 2, "name" => "Ramchandrapur",],
                    ["bn_name" => "মোবারকপুর", "jl_no" => "94", "thana_id" => "457", "survey_id" => 2, "name" => "Mobarakpur",],
                    ["bn_name" => "তেঘরিয়া", "jl_no" => "111", "thana_id" => "457", "survey_id" => 2, "name" => "Teghoria",],
                    ["bn_name" => "খাটুয়াকুমড়ী", "jl_no" => "112", "thana_id" => "457", "survey_id" => 2, "name" => "Khatuakumri",],
                    ["bn_name" => "চককুমড়ী", "jl_no" => "114", "thana_id" => "457", "survey_id" => 2, "name" => "Chokkumri",],
                    ["bn_name" => "কুমড়ী", "jl_no" => "115", "thana_id" => "457", "survey_id" => 2, "name" => "Kumri",],
                    ["bn_name" => "বাজিতখিলা", "jl_no" => "116", "thana_id" => "457", "survey_id" => 2, "name" => "Bajitkhila",],
                    ["bn_name" => "সুলতানপুর", "jl_no" => "117", "thana_id" => "457", "survey_id" => 2, "name" => "Sultanpur",],
                    ["bn_name" => "হোসেনখিলা", "jl_no" => "119", "thana_id" => "457", "survey_id" => 2, "name" => "Hossenkhila",],
                    ["bn_name" => "দাড়িয়াখিলা", "jl_no" => "120", "thana_id" => "457", "survey_id" => 2, "name" => "Dariakhila",],
                    ["bn_name" => "মনকান্দা", "jl_no" => "121", "thana_id" => "457", "survey_id" => 2, "name" => "Monkanda",],
                    ["bn_name" => "মনোহরা", "jl_no" => "122", "thana_id" => "457", "survey_id" => 2, "name" => "Monohora",],
                    ["bn_name" => "মির্জাপুর", "jl_no" => "123", "thana_id" => "457", "survey_id" => 2, "name" => "Mirjapur",],
                    ["bn_name" => "দমদমা", "jl_no" => "124", "thana_id" => "457", "survey_id" => 2, "name" => "Domdoma",],
                    ["bn_name" => "রামকৃষ্ণপুর", "jl_no" => "125", "thana_id" => "457", "survey_id" => 2, "name" => "Ramkrishnopur",],
                    ["bn_name" => "শ্রীকৃষ্ণপুর", "jl_no" => "126", "thana_id" => "457", "survey_id" => 2, "name" => "Srikrishnopur",],
                    ["bn_name" => "নওহাটা", "jl_no" => "127", "thana_id" => "457", "survey_id" => 2, "name" => "Nouhata",],
                    ["bn_name" => "তাতালপুর", "jl_no" => "128", "thana_id" => "457", "survey_id" => 2, "name" => "Tatalpur",],
                    ["bn_name" => "শেরপুর", "jl_no" => "129", "thana_id" => "457", "survey_id" => 2, "name" => "Sherpur",],
                    ["bn_name" => "নারায়নপুর", "jl_no" => "130", "thana_id" => "457", "survey_id" => 2, "name" => "Narayanpur",],
                    ["bn_name" => "ঢাকলহাটি", "jl_no" => "131", "thana_id" => "457", "survey_id" => 2, "name" => "Dhakolhati",],
                    ["bn_name" => "সোনাবরকান্দা", "jl_no" => "132", "thana_id" => "457", "survey_id" => 2, "name" => "Shonaborkanda",],
                    ["bn_name" => "বালিয়া", "jl_no" => "133", "thana_id" => "457", "survey_id" => 2, "name" => "Balia",],
                    ["bn_name" => "লতারিয়া", "jl_no" => "134", "thana_id" => "457", "survey_id" => 2, "name" => "Lotaria",],
                    ["bn_name" => "গণইভরুয়াপাড়া", "jl_no" => "135", "thana_id" => "457", "survey_id" => 2, "name" => "Gonoivhorua",],
                    ["bn_name" => "চৈতনখিলা", "jl_no" => "136", "thana_id" => "457", "survey_id" => 2, "name" => "Choitonkhila",],
                    ["bn_name" => "তারাকান্দি", "jl_no" => "137", "thana_id" => "457", "survey_id" => 2, "name" => "Tarakandi",],
                    ["bn_name" => "বরাটিয়া", "jl_no" => "138", "thana_id" => "457", "survey_id" => 2, "name" => "Boratia",],
                    ["bn_name" => "গাজীর খামার", "jl_no" => "139", "thana_id" => "457", "survey_id" => 2, "name" => "Gajirkhamar",],
                    ["bn_name" => "পাঞ্জরভাঙ্গা", "jl_no" => "140", "thana_id" => "457", "survey_id" => 2, "name" => "Panjorvhanga",],
                    ["bn_name" => "চান্দেরনগর", "jl_no" => "141", "thana_id" => "457", "survey_id" => 2, "name" => "Chandernaga",],
                    ["bn_name" => "কামারিয়া", "jl_no" => "142", "thana_id" => "457", "survey_id" => 2, "name" => "Kamaria",],
                    ["bn_name" => "কোহাকান্দা", "jl_no" => "143", "thana_id" => "457", "survey_id" => 2, "name" => "Kohakanda",],
                    ["bn_name" => "বাকারকান্দা", "jl_no" => "144", "thana_id" => "457", "survey_id" => 2, "name" => "Bakarkanda",],
                    ["bn_name" => "বাদাতেঘরিয়া", "jl_no" => "145", "thana_id" => "457", "survey_id" => 2, "name" => "Badateghoria",],
                    ["bn_name" => "পাকুরিয়া", "jl_no" => "146", "thana_id" => "457", "survey_id" => 2, "name" => "Pakuria",],
                    ["bn_name" => "বয়ড়াপরাণপুর", "jl_no" => "147", "thana_id" => "457", "survey_id" => 2, "name" => "Boiraporanpur",],
                    ["bn_name" => "বলবাড়ি", "jl_no" => "149", "thana_id" => "457", "survey_id" => 2, "name" => "Bolbari",],
                    ["bn_name" => "মধ্যবয়ড়া", "jl_no" => "150", "thana_id" => "457", "survey_id" => 2, "name" => "Moddhoboira",],
                    ["bn_name" => "চরবয়ড়া", "jl_no" => "151", "thana_id" => "457", "survey_id" => 2, "name" => "Charboira",],
                    ["bn_name" => "ভাতশালা", "jl_no" => "152", "thana_id" => "457", "survey_id" => 2, "name" => "Vatsala",],
                    ["bn_name" => "সাপমারী", "jl_no" => "153", "thana_id" => "457", "survey_id" => 2, "name" => "Shapmari",],
                    ["bn_name" => "হাওড়াগড়", "jl_no" => "154", "thana_id" => "457", "survey_id" => 2, "name" => "Haowragor",],
                    ["bn_name" => "হাওড়ানিজ", "jl_no" => "158", "thana_id" => "457", "survey_id" => 2, "name" => "Haowranij",],
                    ["bn_name" => "চরসাপমারী", "jl_no" => "159", "thana_id" => "457", "survey_id" => 2, "name" => "Charshapmari",],
                    ["bn_name" => "ভাটপাড়া", "jl_no" => "160", "thana_id" => "457", "survey_id" => 2, "name" => "Vatpara",],
                    ["bn_name" => "শ্রীরামপুর", "jl_no" => "161", "thana_id" => "457", "survey_id" => 2, "name" => "Srirampur",],
                    ["bn_name" => "সূর্য্যদি", "jl_no" => "162", "thana_id" => "457", "survey_id" => 2, "name" => "Shurjodi",],
                    ["bn_name" => "তিরছা", "jl_no" => "163", "thana_id" => "457", "survey_id" => 2, "name" => "Tirsa",],
                    ["bn_name" => "বারঘরিয়া", "jl_no" => "164", "thana_id" => "457", "survey_id" => 2, "name" => "Baroghoria",],
                    ["bn_name" => "চককবিরপুর", "jl_no" => "165", "thana_id" => "457", "survey_id" => 2, "name" => "Chokkobirpur",],
                    ["bn_name" => "আলিনাপাড়া", "jl_no" => "166", "thana_id" => "457", "survey_id" => 2, "name" => "Alinapara",],
                    ["bn_name" => "কবিরপুর আন্ধারিয়া", "jl_no" => "167", "thana_id" => "457", "survey_id" => 2, "name" => "Kabirpurandharia",],
                    ["bn_name" => "রঘুনাথপুর", "jl_no" => "168", "thana_id" => "457", "survey_id" => 2, "name" => "Roghunathpur",],
                    ["bn_name" => "চরপক্ষীমারী", "jl_no" => "169", "thana_id" => "457", "survey_id" => "4", "name" => "Charpokkhimari",],
                    ["bn_name" => "জঙ্গলদী", "jl_no" => "170", "thana_id" => "457", "survey_id" => 2, "name" => "Jonggoldi",],
                    ["bn_name" => "চরজঙ্গলদী", "jl_no" => "171", "thana_id" => "457", "survey_id" => 2, "name" => "Char Jonggoldi",],
                    ["bn_name" => "সুবণেরচর", "jl_no" => "172", "thana_id" => "457", "survey_id" => 2, "name" => "Shubornerchar",],
                    ["bn_name" => "কুমড়ারচর", "jl_no" => "173", "thana_id" => "457", "survey_id" => 2, "name" => "Kumrarchar",],
                    ["bn_name" => "ধোবারচর", "jl_no" => "174", "thana_id" => "457", "survey_id" => 2, "name" => "Dhobarchar",],
                    ["bn_name" => "ইলশা", "jl_no" => "175", "thana_id" => "457", "survey_id" => 2, "name" => "Elsha",],
                    ["bn_name" => "ছনকান্দাকুঠুরাকান্দা", "jl_no" => "178", "thana_id" => "457", "survey_id" => 2, "name" => "Sonkandakuthurakanda",],
                    ["bn_name" => "গোপালপুর", "jl_no" => "179", "thana_id" => "457", "survey_id" => 2, "name" => "Gopalpur",],
                    ["bn_name" => "টিকারচর", "jl_no" => "180", "thana_id" => "457", "survey_id" => 2, "name" => "Tikarchar",],
                    ["bn_name" => "দিঘলদী", "jl_no" => "181", "thana_id" => "457", "survey_id" => 2, "name" => "Digoldi",],
                    ["bn_name" => "কৃষ্ণপুর", "jl_no" => "182", "thana_id" => "457", "survey_id" => 2, "name" => "Krisnopur",],
                    ["bn_name" => "মোচারেরচর", "jl_no" => "183", "thana_id" => "457", "survey_id" => 2, "name" => "Mocharerchor",],
                    ["bn_name" => "চকসাহাব্দী", "jl_no" => "184", "thana_id" => "457", "survey_id" => 2, "name" => "Choksahabdi",],
                    ["bn_name" => "বলাইরচর", "jl_no" => "185", "thana_id" => "457", "survey_id" => 2, "name" => "Bolaerchar",],
                    ["bn_name" => "ঘুঘুরাকান্দি", "jl_no" => "186", "thana_id" => "457", "survey_id" => 2, "name" => "Ghughurakandi",],
                    ["bn_name" => "চররাম জগন্নাথ", "jl_no" => "187", "thana_id" => "457", "survey_id" => 2, "name" => "Charramjogonnath",],
                    ["bn_name" => "কামারের চর", "jl_no" => "188", "thana_id" => "457", "survey_id" => 2, "name" => "Kamarerchar",],
            // End::Sherpur Sadar-457 CS-2

            // Start:: Sherpur Sadar-457 CS-4
                ["bn_name" => "চরপক্ষীমারী", "jl_no" => "7", "thana_id" => "457", "survey_id" => "4", "name" => "Charpokkhimari",],
            // End:: Sherpur Sadar-457 CS-4

            // Start:: Sherpur Sadar-457 CS-5
                    ["bn_name" => "সন্ন্যাসীরচর", "jl_no" => "1", "thana_id" => "457", "survey_id" => "5", "name" => "Sonnashirchar",],
                    ["bn_name" => "হেরুয়া", "jl_no" => "2", "thana_id" => "457", "survey_id" => 5, "name" => "Herua",],
                    ["bn_name" => "কামারের চর", "jl_no" => "6", "thana_id" => "457", "survey_id" => 5, "name" => "Kamarerchar",],
                    ["bn_name" => "চরপক্ষীমারী", "jl_no" => "7", "thana_id" => "457", "survey_id" => 5, "name" => "Charpokkhimari",],
                    ["bn_name" => "টিকারচর", "jl_no" => "8", "thana_id" => "457", "survey_id" => 5, "name" => "Tikarchar",],
                    ["bn_name" => "মুকসুদপুর", "jl_no" => "11", "thana_id" => "457", "survey_id" => 5, "name" => "Muksudpur",],
                    ["bn_name" => "হরিণধরা", "jl_no" => "12", "thana_id" => "457", "survey_id" => 5, "name" => "Horindhora",],
                    ["bn_name" => "চরভাবনা", "jl_no" => "13", "thana_id" => "457", "survey_id" => 5, "name" => "Charvabna",],
                    ["bn_name" => "মোচারেরচর", "jl_no" => "14", "thana_id" => "457", "survey_id" => 5, "name" => "Mocharerchor",],
                    ["bn_name" => "জোতকসবা", "jl_no" => "17", "thana_id" => "457", "survey_id" => 5, "name" => "Jotkoshba",],
                    ["bn_name" => "যোগনীবাগ", "jl_no" => "18", "thana_id" => "457", "survey_id" => 5, "name" => "Jognibag",],
                    ["bn_name" => "রামচন্দ্রপুর", "jl_no" => "20", "thana_id" => "457", "survey_id" => 5, "name" => "Ramchandrapur",],
                    ["bn_name" => "মোবারকপুর", "jl_no" => "21", "thana_id" => "457", "survey_id" => 5, "name" => "Mobarakpur",],
                    ["bn_name" => "রামকৃষ্ণপুর", "jl_no" => "22", "thana_id" => "457", "survey_id" => 5, "name" => "Ramkrishnopur",],
                    ["bn_name" => "শেরপুর", "jl_no" => "23", "thana_id" => "457", "survey_id" => 5, "name" => "Sherpur",],
                    ["bn_name" => "শ্রীকৃষ্ণপুর", "jl_no" => "24", "thana_id" => "457", "survey_id" => 5, "name" => "Srikrishnopur",],
                    ["bn_name" => "নওহাটা", "jl_no" => "25", "thana_id" => "457", "survey_id" => 5, "name" => "Nouhata",],
                    ["bn_name" => "তাতালপুর", "jl_no" => "26", "thana_id" => "457", "survey_id" => 5, "name" => "Tatalpur",],
                    ["bn_name" => "মনোহরা", "jl_no" => "27", "thana_id" => "457", "survey_id" => 5, "name" => "Monohora",],
                    ["bn_name" => "দমদমা", "jl_no" => "28", "thana_id" => "457", "survey_id" => 5, "name" => "Domdoma",],
                    ["bn_name" => "মির্জাপুর", "jl_no" => "29", "thana_id" => "457", "survey_id" => 5, "name" => "Mirjapur",],
                    ["bn_name" => "বাজিতখিলা", "jl_no" => "31", "thana_id" => "457", "survey_id" => 5, "name" => "Bajitkhila",],
                    ["bn_name" => "কুমড়ী", "jl_no" => "32", "thana_id" => "457", "survey_id" => 5, "name" => "Kumri",],
                    ["bn_name" => "গাজীর খামার", "jl_no" => "36", "thana_id" => "457", "survey_id" => 5, "name" => "Gajirkhamar",],
                    ["bn_name" => "বরাটিয়া", "jl_no" => "38", "thana_id" => "457", "survey_id" => 5, "name" => "Boratia",],
                    ["bn_name" => "তাড়াগড়", "jl_no" => "39", "thana_id" => "457", "survey_id" => 5, "name" => "Taragor",],
                    ["bn_name" => "চৈতনখিলা", "jl_no" => "40", "thana_id" => "457", "survey_id" => 5, "name" => "Choitonkhila",],
                    ["bn_name" => "গণইভরুয়াপাড়া", "jl_no" => "48", "thana_id" => "457", "survey_id" => 5, "name" => "Gonoivhorua",],
                    ["bn_name" => "ঢাকলহাটি", "jl_no" => "49", "thana_id" => "457", "survey_id" => 5, "name" => "Dhakolhati",],
                    ["bn_name" => "শেখহাটি", "jl_no" => "50", "thana_id" => "457", "survey_id" => 5, "name" => "Shekhhati",],
                    ["bn_name" => "নারায়নপুর", "jl_no" => "51", "thana_id" => "457", "survey_id" => 5, "name" => "Narayanpur",],
                    ["bn_name" => "বয়ড়াপরাণপুর", "jl_no" => "52", "thana_id" => "457", "survey_id" => 5, "name" => "Boiraporanpur",],
                    ["bn_name" => "বলবাড়ি", "jl_no" => "53", "thana_id" => "457", "survey_id" => 5, "name" => "Bolbari",],
                    ["bn_name" => "ভাতশালা", "jl_no" => "55", "thana_id" => "457", "survey_id" => 5, "name" => "Vatsala",],
                    ["bn_name" => "ছনকান্দাকুঠুরাকান্দা", "jl_no" => "57", "thana_id" => "457", "survey_id" => 5, "name" => "Sonkandakuthurakanda",],
                    ["bn_name" => "লছমনপুর", "jl_no" => "59", "thana_id" => "457", "survey_id" => 5, "name" => "Losmonpur",],
                    ["bn_name" => "চরপাড়া খুনুয়া", "jl_no" => "76", "thana_id" => "457", "survey_id" => 5, "name" => "Chorpara Khunua",],
                    ["bn_name" => "সাপমারী", "jl_no" => "86", "thana_id" => "457", "survey_id" => 5, "name" => "Shapmari",],
                    ["bn_name" => "চররাম জগন্নাথ", "jl_no" => "104", "thana_id" => "457", "survey_id" => 5, "name" => "Charramjogonnath",],
            // End::Sherpur Sadar-457 CS-5

            // Start:: Sherpur Sadar-457 CS-7
                ["bn_name" => "চরপক্ষীমারী", "jl_no" => "7", "thana_id" => "457", "survey_id" => "7", "name" => "Charpokkhimari",],
            // End:: Sherpur Sadar-457 CS-7

            // Start:: Nalitabari-458 SA-1
                    ["bn_name" => "ঢেকরাপাড়া", "jl_no" => "22", "thana_id" => "458", "survey_id" => "1", "name" => "Dhekrapara",],
                    ["bn_name" => "রাতকুচি", "jl_no" => "27", "thana_id" => "458", "survey_id" => "1", "name" => "Sidhuli",],
                    ["bn_name" => "ফুলপুর", "jl_no" => "212", "thana_id" => "458", "survey_id" => "2", "name" => "Purba Beltoil",],
                    ["bn_name" => "গেদালুপাড়া", "jl_no" => "57", "thana_id" => "458", "survey_id" => "1", "name" => "Tantar",],
                    ["bn_name" => "কেরেঙ্গাপাড়া", "jl_no" => "58", "thana_id" => "458", "survey_id" => "1", "name" => "Mandaliapara",],
                    ["bn_name" => "কাউলারা", "jl_no" => "61", "thana_id" => "458", "survey_id" => "1", "name" => "Kerengapara",],
                    ["bn_name" => "ঘাইলারা", "jl_no" => "62", "thana_id" => "458", "survey_id" => "1", "name" => "Kakarkandi",],
                    ["bn_name" => "পলাশিয়া", "jl_no" => "59", "thana_id" => "458", "survey_id" => "1", "name" => "Baruajani",],
                    ["bn_name" => "গোজাকুড়া", "jl_no" => "74", "thana_id" => "458", "survey_id" => "1", "name" => "Krishnapur Debipur",],
            // End:: Nalitabari-458 SA-1

            // Start:: Nalitabari-458 SA-5
                    ["bn_name" => "সমসচুড়া", "jl_no" => "1", "thana_id" => "458", "survey_id" => 5, "name" => "Samaschura",],
                    ["bn_name" => "লক্ষীকুড়া", "jl_no" => "2", "thana_id" => "458", "survey_id" => 5, "name" => "Laksmikura",],
                    ["bn_name" => "ধুপাকুড়া", "jl_no" => "3", "thana_id" => "458", "survey_id" => 5, "name" => "Dhupakura",],
                    ["bn_name" => "তোয়ালকুচি", "jl_no" => "4", "thana_id" => "458", "survey_id" => 5, "name" => "Toalkuchi",],
                    ["bn_name" => "উদলাকুচি", "jl_no" => 5, "thana_id" => "458", "survey_id" => 5, "name" => "Udlakuchi",],
                    ["bn_name" => "বন্ধধারা", "jl_no" => "6", "thana_id" => "458", "survey_id" => 5, "name" => "Bandhadhara",],
                    ["bn_name" => "বাইগর পাড়া", "jl_no" => "7", "thana_id" => "458", "survey_id" => 5, "name" => "Baigarpara",],
                    ["bn_name" => "নন্নী", "jl_no" => "8", "thana_id" => "458", "survey_id" => 5, "name" => "Nonni",],
                    ["bn_name" => "ছাইছাকুড়া", "jl_no" => "9", "thana_id" => "458", "survey_id" => 5, "name" => "Chaisakura",],
                    ["bn_name" => "পোড়াগাঁও", "jl_no" => "10", "thana_id" => "458", "survey_id" => 5, "name" => "Poragong",],
                    ["bn_name" => "বাতকুচি", "jl_no" => "11", "thana_id" => "458", "survey_id" => 5, "name" => "Batkuchi",],
                    ["bn_name" => "বরুঙ্গা", "jl_no" => "12", "thana_id" => "458", "survey_id" => 5, "name" => "Burunga",],
                    ["bn_name" => "খলচাঁন্দা", "jl_no" => "14", "thana_id" => "458", "survey_id" => 5, "name" => "khalchanda",],
                    ["bn_name" => "ডালুকোনা", "jl_no" => "14", "thana_id" => "458", "survey_id" => 5, "name" => "",],
                    ["bn_name" => "আন্ধারু পাড়া বাইগর পাড়া", "jl_no" => "15", "thana_id" => "458", "survey_id" => 5, "name" => "Andarupara Baigarpara",],
                    ["bn_name" => "পলাশিকুড়া", "jl_no" => "16", "thana_id" => "458", "survey_id" => 5, "name" => "Palashikura",],
                    ["bn_name" => "বনারপাড়া", "jl_no" => "17", "thana_id" => "458", "survey_id" => 5, "name" => "Banarpara",],
                    ["bn_name" => "বেকীকুড়া", "jl_no" => "18", "thana_id" => "458", "survey_id" => 5, "name" => "Bekikura",],
                    ["bn_name" => "তাজুরাবাদ", "jl_no" => "19", "thana_id" => "458", "survey_id" => 5, "name" => "Tazurabad",],
                    ["bn_name" => "কুতুবাকুড়া", "jl_no" => "20", "thana_id" => "458", "survey_id" => 5, "name" => "kutubakura",],
                    ["bn_name" => "অভয়পুর", "jl_no" => "21", "thana_id" => "458", "survey_id" => 5, "name" => "Avoipur",],
                    ["bn_name" => "নিশ্চিন্তপুর", "jl_no" => "24", "thana_id" => "458", "survey_id" => 5, "name" => "Nishchintapur",],
                    ["bn_name" => "কাচিমৌ", "jl_no" => "24", "thana_id" => "458", "survey_id" => 5, "name" => "Kachimou",],
                    ["bn_name" => "বনকুড়া", "jl_no" => "25", "thana_id" => "458", "survey_id" => 5, "name" => "Bankura",],
                    ["bn_name" => "মৌওয়াকুড়া", "jl_no" => "26", "thana_id" => "458", "survey_id" => 5, "name" => "Noiabil",],
                    ["bn_name" => "খলিসাকুড়া", "jl_no" => "28", "thana_id" => "458", "survey_id" => 5, "name" => "Badlakura",],
                    ["bn_name" => "আন্ধারুপাড়া", "jl_no" => "29", "thana_id" => "458", "survey_id" => 5, "name" => "Manpara",],
                    ["bn_name" => "সিধুলী", "jl_no" => "40", "thana_id" => "458", "survey_id" => 5, "name" => "Vatpur",],
                    ["bn_name" => "কয়রাকুড়া চিহরতলা", "jl_no" => "41", "thana_id" => "458", "survey_id" => 5, "name" => "Kayrakuri Chihortola",],
                    ["bn_name" => "ভটপুর", "jl_no" => "42", "thana_id" => "458", "survey_id" => 5, "name" => "Dudhkura",],
                    ["bn_name" => "মানিক চাঁদপাড়া", "jl_no" => "44", "thana_id" => "458", "survey_id" => 5, "name" => "Hatipagar",],
                    ["bn_name" => "বাদলাকুড়া", "jl_no" => "44", "thana_id" => "458", "survey_id" => 5, "name" => "Manik Chadpara",],
                    ["bn_name" => "মানপাড়া", "jl_no" => "45", "thana_id" => "458", "survey_id" => 5, "name" => "Chatkia",],
                    ["bn_name" => "নয়াবিল", "jl_no" => "46", "thana_id" => "458", "survey_id" => 5, "name" => "Rupakura",],
                    ["bn_name" => "রুপাকুড়া", "jl_no" => "44", "thana_id" => "458", "survey_id" => 5, "name" => "Dauwakura",],
                    ["bn_name" => "সেকেরকুড়া", "jl_no" => "48", "thana_id" => "458", "survey_id" => 5, "name" => "sekerkura",],
                    ["bn_name" => "ডাউয়াকুড়া", "jl_no" => "49", "thana_id" => "458", "survey_id" => 5, "name" => "Dawdhara Katabari",],
                    ["bn_name" => "চাঁটকিয়া", "jl_no" => "40", "thana_id" => "458", "survey_id" => 5, "name" => "Nakugong",],
                    ["bn_name" => "দুধকুড়া", "jl_no" => "41", "thana_id" => "458", "survey_id" => 5, "name" => "Dalukuna",],
                    ["bn_name" => "হাতীপাগাড়", "jl_no" => "42", "thana_id" => "458", "survey_id" => 5, "name" => "",],
                    ["bn_name" => "দাওধারা কাটাবাড়ী", "jl_no" => "44", "thana_id" => "458", "survey_id" => 5, "name" => "Sagardi Krishnapatti",],
                    ["bn_name" => "নাকুগাঁও", "jl_no" => "44", "thana_id" => "458", "survey_id" => 5, "name" => "",],
                    ["bn_name" => "কালাকুমা", "jl_no" => "45", "thana_id" => "458", "survey_id" => 5, "name" => "Andarupara",],
                    ["bn_name" => "তারনী", "jl_no" => "46", "thana_id" => "458", "survey_id" => 5, "name" => "Khalisakura",],
                    ["bn_name" => "পানিহাতা", "jl_no" => "47", "thana_id" => "458", "survey_id" => 5, "name" => "Ratkuchi",],
                    ["bn_name" => "মায়াঘাসী", "jl_no" => "48", "thana_id" => "458", "survey_id" => 5, "name" => "Mouakura",],
                    ["bn_name" => "রামচন্দ্রকুড়া", "jl_no" => "49", "thana_id" => "458", "survey_id" => 5, "name" => "Tarini",],
                    ["bn_name" => "বিশগিরী পাড়া", "jl_no" => "50", "thana_id" => "458", "survey_id" => 5, "name" => "Kalakuma",],
                    ["bn_name" => "রাজারামকুড়া", "jl_no" => "51", "thana_id" => "458", "survey_id" => 5, "name" => "Panihata",],
                    ["bn_name" => "পূর্ব বেলতৈল", "jl_no" => "52", "thana_id" => "458", "survey_id" => 5, "name" => "Mayaghasi",],
                    ["bn_name" => "তন্তর", "jl_no" => "53", "thana_id" => "458", "survey_id" => 5, "name" => "Bishgiripara",],
                    ["bn_name" => "মন্ডলীয়পাড়া", "jl_no" => "54", "thana_id" => "458", "survey_id" => 5, "name" => "Ramchadrakura",],
                    ["bn_name" => "ঘাগপাড়া", "jl_no" => "55", "thana_id" => "458", "survey_id" => 5, "name" => "Rajaramkura",],
                    ["bn_name" => "কলসপাড়", "jl_no" => "56", "thana_id" => "458", "survey_id" => 5, "name" => "Shimultala",],
                    ["bn_name" => "গাগলাজানী", "jl_no" => "57", "thana_id" => "458", "survey_id" => 5, "name" => "Sonnasibita",],
                    ["bn_name" => "সূর্য্যনগর", "jl_no" => "58", "thana_id" => "458", "survey_id" => 5, "name" => "Umtabagber",],
                    ["bn_name" => "বড়ডুবী", "jl_no" => "59", "thana_id" => "458", "survey_id" => 5, "name" => "Baradubi",],
                    ["bn_name" => "বিন্নীবাড়ী", "jl_no" => "60", "thana_id" => "458", "survey_id" => 5, "name" => "Sohagpur",],
                    ["bn_name" => "দোহালিয়া", "jl_no" => "61", "thana_id" => "458", "survey_id" => 5, "name" => "Dohalia",],
                    ["bn_name" => "রাজনগর", "jl_no" => "62", "thana_id" => "458", "survey_id" => 5, "name" => "Rajnagar",],
                    ["bn_name" => "শালমারা", "jl_no" => "63", "thana_id" => "458", "survey_id" => 5, "name" => "Kawlara",],
                    ["bn_name" => "পিঠাপুন্নী", "jl_no" => "64", "thana_id" => "458", "survey_id" => 5, "name" => "Palashia",],
                    ["bn_name" => "পূর্ব মানিককুড়া", "jl_no" => "65", "thana_id" => "458", "survey_id" => 5, "name" => "Ghailara",],
                    ["bn_name" => "বরুয়াজানি", "jl_no" => "66", "thana_id" => "458", "survey_id" => 5, "name" => "Phulpur",],
                    ["bn_name" => "কাকরকান্দি", "jl_no" => "67", "thana_id" => "458", "survey_id" => 5, "name" => "Ghugpara",],
                    ["bn_name" => "সোহাগপুর", "jl_no" => "68", "thana_id" => "458", "survey_id" => 5, "name" => "Gedalupara",],
                    ["bn_name" => "ভালুকাকুড়া", "jl_no" => "69", "thana_id" => "458", "survey_id" => 5, "name" => "Pithapuni",],
                    ["bn_name" => "কৃষ্ণপুর দেবীপুর", "jl_no" => "70", "thana_id" => "458", "survey_id" => 5, "name" => "Vedikura",],
                    ["bn_name" => "সিঙ্গুয়া রুপনারায়ন কুড়া", "jl_no" => "71", "thana_id" => "458", "survey_id" => 5, "name" => "Valukakura",],
                    ["bn_name" => "পাইকতলা", "jl_no" => "72", "thana_id" => "458", "survey_id" => 5, "name" => "Chinamara",],
                    ["bn_name" => "কাউয়াকুড়ি", "jl_no" => "73", "thana_id" => "458", "survey_id" => 5, "name" => "Nalitabari",],
                    ["bn_name" => "আয়নাতলী", "jl_no" => "75", "thana_id" => "458", "survey_id" => 5, "name" => "Singua Rupnaraonkura",],
                    ["bn_name" => "খুজিউড়া", "jl_no" => "76", "thana_id" => "458", "survey_id" => 5, "name" => "Binnibari",],
                    ["bn_name" => "জয়নদ্দিন পাড়া", "jl_no" => "77", "thana_id" => "458", "survey_id" => 5, "name" => "Purba Manikkura",],
                    ["bn_name" => "ভেদিকুড়া", "jl_no" => "78", "thana_id" => "458", "survey_id" => 5, "name" => "Khujiura",],
                    ["bn_name" => "চান্দের নন্নী", "jl_no" => "79", "thana_id" => "458", "survey_id" => 5, "name" => "Shalmara",],
                    ["bn_name" => "চিনামারা", "jl_no" => "80", "thana_id" => "458", "survey_id" => 5, "name" => "Chander Nonni",],
                    ["bn_name" => "নালিতাবাড়ী", "jl_no" => "81", "thana_id" => "458", "survey_id" => 5, "name" => "Jaynaddinpara",],
                    ["bn_name" => "গোবিন্দ নগর ", "jl_no" => "82", "thana_id" => "458", "survey_id" => 5, "name" => "Kapashia",],
                    ["bn_name" => "সিটপাড়া", "jl_no" => "83", "thana_id" => "458", "survey_id" => 5, "name" => "Jogania",],
                    ["bn_name" => "গড়কান্দা", "jl_no" => "84", "thana_id" => "458", "survey_id" => 5, "name" => "Bathuarkanda",],
                    ["bn_name" => "গোবিন্দনগর কালিনগর", "jl_no" => "85", "thana_id" => "458", "survey_id" => 5, "name" => "Baitkamari",],
                    ["bn_name" => "শিমুলতলা", "jl_no" => "86", "thana_id" => "458", "survey_id" => 5, "name" => "Sitpara",],
                    ["bn_name" => "উমতাবাঘবেড়", "jl_no" => "87", "thana_id" => "458", "survey_id" => 5, "name" => "Gabindanagar",],
                    ["bn_name" => "সালেহাবাদ", "jl_no" => "88", "thana_id" => "458", "survey_id" => 5, "name" => "Salehabad",],
                    ["bn_name" => "চাঁদগাও", "jl_no" => "127", "thana_id" => "458", "survey_id" => 5, "name" => "Chadgaon",],
                    ["bn_name" => "আমলাতলী", "jl_no" => "128", "thana_id" => "458", "survey_id" => 5, "name" => "Amlatoli",],
                    ["bn_name" => "রাণীগাঁও", "jl_no" => "162", "thana_id" => "458", "survey_id" => 5, "name" => "Gabindanagar Kalinagar",],
                    ["bn_name" => "সন্যাসীভিটা", "jl_no" => "163", "thana_id" => "458", "survey_id" => 5, "name" => "Gorkanda",],
                    ["bn_name" => "সাগরদী-কৃষ্ণপট্টি", "jl_no" => "164", "thana_id" => "458", "survey_id" => 5, "name" => "",],
                    ["bn_name" => "পাঁচগাঁও", "jl_no" => "165", "thana_id" => "458", "survey_id" => 5, "name" => "Surjanagar",],
                    ["bn_name" => "বালুঘাটা", "jl_no" => "166", "thana_id" => "458", "survey_id" => 5, "name" => "Kalaspar",],
                    ["bn_name" => "নাকসী", "jl_no" => "167", "thana_id" => "458", "survey_id" => 5, "name" => "Ranigong",],
                    ["bn_name" => "বাথুয়ার কান্দা", "jl_no" => "168", "thana_id" => "458", "survey_id" => 5, "name" => "Konnagar",],
                    ["bn_name" => "বাইটকামারী", "jl_no" => "169", "thana_id" => "458", "survey_id" => 5, "name" => "Gujakura",],
                    ["bn_name" => "যোগানিয়া", "jl_no" => "170", "thana_id" => "458", "survey_id" => 5, "name" => "Ainatali",],
                    ["bn_name" => "কাপাশিয়া", "jl_no" => "171", "thana_id" => "458", "survey_id" => 5, "name" => "Morichpuran",],
                    ["bn_name" => "কোন্নগর", "jl_no" => "172", "thana_id" => "458", "survey_id" => 5, "name" => "Paikatala",],
                    ["bn_name" => "মরিচপুরান", "jl_no" => "173", "thana_id" => "458", "survey_id" => 5, "name" => "Kawakuri",],
            // End:: Nalitabari-458 SA-5

            // Start:: Sreebordi-459 SA-1
                ["bn_name" => "গড়গড়িয়া", "jl_no" => "50", "thana_id" => "459", "survey_id" => "1", "name" => "Gorgoria",],
                ["bn_name" => "ছেউরিয়া", "jl_no" => "60", "thana_id" => "459", "survey_id" => "1", "name" => "Shauria",],
            // End:: Sreebordi-459 SA-1

            // Start:: Sreebordi-459 SA-5
                    ["bn_name" => "মোরগাচুরা", "jl_no" => "5", "thana_id" => "459", "survey_id" => "5", "name" => "Murgachora",],
                    ["bn_name" => "খোশালপুর", "jl_no" => "8", "thana_id" => "459", "survey_id" => "5", "name" => "Khoshalpur",],
                    ["bn_name" => "সরকারদি", "jl_no" => "9", "thana_id" => "459", "survey_id" => "5", "name" => "Shakardi",],
                    ["bn_name" => "খাটিয়াডাঙ্গা", "jl_no" => "10", "thana_id" => "459", "survey_id" => 5, "name" => "Khatiadangga",],
                    ["bn_name" => "কাকিলাকুড়া", "jl_no" => "11", "thana_id" => "459", "survey_id" => 5, "name" => "Kakilakura",],
                    ["bn_name" => "সিংগাবরুনা", "jl_no" => "12", "thana_id" => "459", "survey_id" => 5, "name" => "Singaboruna",],
                    ["bn_name" => "বরইকুচি", "jl_no" => "13", "thana_id" => "459", "survey_id" => 5, "name" => "Boraikuchi",],
                    ["bn_name" => "মাটিফাটা", "jl_no" => "14", "thana_id" => "459", "survey_id" => 5, "name" => "Matifata",],
                    ["bn_name" => "সগুনা", "jl_no" => "15", "thana_id" => "459", "survey_id" => 5, "name" => "Soguna",],
                    ["bn_name" => "জঙ্গলামাধবপুর", "jl_no" => "16", "thana_id" => "459", "survey_id" => 5, "name" => "Jolonggamadoppur",],
                    ["bn_name" => "কর্নঝোড়া", "jl_no" => "19", "thana_id" => "459", "survey_id" => 5, "name" => "Kornojura",],
                    ["bn_name" => "জুলগাও", "jl_no" => "20", "thana_id" => "459", "survey_id" => 5, "name" => "Julgue",],
                    ["bn_name" => "হারিয়া", "jl_no" => "21", "thana_id" => "459", "survey_id" => 5, "name" => "Haria",],
                    ["bn_name" => "বালিজুরী", "jl_no" => "22", "thana_id" => "459", "survey_id" => 5, "name" => "Balijuri",],
                    ["bn_name" => "হলুয়াহাটি", "jl_no" => "23", "thana_id" => "459", "survey_id" => 5, "name" => "Haluahati",],
                    ["bn_name" => "মালাকুচা", "jl_no" => "24", "thana_id" => "459", "survey_id" => 5, "name" => "Malakocha",],
                    ["bn_name" => "হাতীবর", "jl_no" => "25", "thana_id" => "459", "survey_id" => 5, "name" => "Hatibor",],
                    ["bn_name" => "তেতুলিয়া", "jl_no" => "26", "thana_id" => "459", "survey_id" => 5, "name" => "Tatulia",],
                    ["bn_name" => "বিলভরট", "jl_no" => "27", "thana_id" => "459", "survey_id" => 5, "name" => "Bilvorat",],
                    ["bn_name" => "চক্রপুর", "jl_no" => "28", "thana_id" => "459", "survey_id" => 5, "name" => "Chakropur",],
                    ["bn_name" => "গোবিন্দপুর", "jl_no" => "29", "thana_id" => "459", "survey_id" => 5, "name" => "Gobindropur",],
                    ["bn_name" => "বাঘহাতা", "jl_no" => "30", "thana_id" => "459", "survey_id" => 5, "name" => "Baghata",],
                    ["bn_name" => "উত্তর ঘোনাপাড়া", "jl_no" => "31", "thana_id" => "459", "survey_id" => 5, "name" => "Uttorgunapara",],
                    ["bn_name" => "ভায়াডাঙ্গ", "jl_no" => "32", "thana_id" => "459", "survey_id" => 5, "name" => "Vaidangga",],
                    ["bn_name" => "টেঙ্গরপাড়া", "jl_no" => "33", "thana_id" => "459", "survey_id" => 5, "name" => "Tangorpara",],
                    ["bn_name" => "শিমূলকুচী", "jl_no" => "34", "thana_id" => "459", "survey_id" => 5, "name" => "Shimulkuchi",],
                    ["bn_name" => "রাণি শিমূল", "jl_no" => "35", "thana_id" => "459", "survey_id" => 5, "name" => "Ranishimul",],
                    ["bn_name" => "জানকিখিলা", "jl_no" => "36", "thana_id" => "459", "survey_id" => 5, "name" => "Jankikhila",],
                    ["bn_name" => "বকচর", "jl_no" => "37", "thana_id" => "459", "survey_id" => 5, "name" => "Bokchor",],
                    ["bn_name" => "চককাউরিয়া", "jl_no" => "38", "thana_id" => "459", "survey_id" => 5, "name" => "Chakkawria",],
                    ["bn_name" => "ছনকান্দা", "jl_no" => "39", "thana_id" => "459", "survey_id" => 5, "name" => "Shankanda",],
                    ["bn_name" => "শ্রীবরদী", "jl_no" => "40", "thana_id" => "459", "survey_id" => 5, "name" => "Sreebordi",],
                    ["bn_name" => "শ্রীবরদী-শম্ভুগঞ্জ", "jl_no" => "41", "thana_id" => "459", "survey_id" => 5, "name" => "Sreebordi-shombugongo",],
                    ["bn_name" => "দহেরপাড়", "jl_no" => "42", "thana_id" => "459", "survey_id" => 5, "name" => "Doherpar",],
                    ["bn_name" => "মামদামারী", "jl_no" => "43", "thana_id" => "459", "survey_id" => 5, "name" => "Mamdhamari",],
                    ["bn_name" => "সেকদী", "jl_no" => "44", "thana_id" => "459", "survey_id" => 5, "name" => "shakdi",],
                    ["bn_name" => "মথুরাদী", "jl_no" => "45", "thana_id" => "459", "survey_id" => 5, "name" => "Mothoradi",],
                    ["bn_name" => "জালকাটা", "jl_no" => "46", "thana_id" => "459", "survey_id" => 5, "name" => "Jalkata",],
                    ["bn_name" => "তাতীহাটি", "jl_no" => "47", "thana_id" => "459", "survey_id" => 5, "name" => "Tathihati",],
                    ["bn_name" => "বড়পোড়াগড়", "jl_no" => "48", "thana_id" => "459", "survey_id" => 5, "name" => "Boropuragor",],
                    ["bn_name" => "সাইটকাকড়া", "jl_no" => "49", "thana_id" => "459", "survey_id" => 5, "name" => "Shaitkakra",],
                    ["bn_name" => "গিলাগাছা", "jl_no" => "51", "thana_id" => "459", "survey_id" => 5, "name" => "Gilagacha",],
                    ["bn_name" => "বাদেঘোনাপাড়া", "jl_no" => "52", "thana_id" => "459", "survey_id" => 5, "name" => "Badagunapara",],
                    ["bn_name" => "জংগলখিলা", "jl_no" => "53", "thana_id" => "459", "survey_id" => 5, "name" => "Gongolkhila",],
                    ["bn_name" => "শংকরঘোষ", "jl_no" => "54", "thana_id" => "459", "survey_id" => 5, "name" => "Shankorgush",],
                    ["bn_name" => "ভারেরা", "jl_no" => "55", "thana_id" => "459", "survey_id" => 5, "name" => "Varera",],
                    ["bn_name" => "মাটিয়াকুড়া", "jl_no" => "56", "thana_id" => "459", "survey_id" => 5, "name" => "Matiakura",],
                    ["bn_name" => "ধাতুয়া", "jl_no" => "57", "thana_id" => "459", "survey_id" => 5, "name" => "Dhatua",],
                    ["bn_name" => "আশ্বিনাকান্দা", "jl_no" => "58", "thana_id" => "459", "survey_id" => 5, "name" => "Asbina kanda",],
                    ["bn_name" => "মাদারপুর", "jl_no" => "59", "thana_id" => "459", "survey_id" => 5, "name" => "Madarpur",],
                    ["bn_name" => "ভেলুয়া", "jl_no" => "60", "thana_id" => "459", "survey_id" => 5, "name" => "Velaua",],
                    ["bn_name" => "শিমূলচড়া", "jl_no" => "61", "thana_id" => "459", "survey_id" => 5, "name" => "Shimulcura",],
                    ["bn_name" => "লক্ষীডাংরী", "jl_no" => "62", "thana_id" => "459", "survey_id" => 5, "name" => "Laksidanri",],
                    ["bn_name" => "চকবন্দী", "jl_no" => "63", "thana_id" => "459", "survey_id" => 5, "name" => "Chakbandi",],
                    ["bn_name" => "বারারচর", "jl_no" => "64", "thana_id" => "459", "survey_id" => 5, "name" => "Bararacara",],
                    ["bn_name" => "চরহাবর", "jl_no" => "65", "thana_id" => "459", "survey_id" => 5, "name" => "Chorhabor",],
                    ["bn_name" => "ঢনঢনিয়া", "jl_no" => "66", "thana_id" => "459", "survey_id" => 5, "name" => "Dhanadhnia",],
                    ["bn_name" => "লঙ্গরপাড়া", "jl_no" => "67", "thana_id" => "459", "survey_id" => 5, "name" => "Langarpara",],
                    ["bn_name" => "পোড়াগড়", "jl_no" => "68", "thana_id" => "459", "survey_id" => 5, "name" => "Puragor",],
                    ["bn_name" => "বীরবান্দা", "jl_no" => "69", "thana_id" => "459", "survey_id" => 5, "name" => "Birbanda",],
                    ["bn_name" => "খড়িয়াকাজিরচর", "jl_no" => "70", "thana_id" => "459", "survey_id" => 5, "name" => "Kariya kazirchar",],
                    ["bn_name" => "ঝিনিয়া", "jl_no" => "71", "thana_id" => "459", "survey_id" => 5, "name" => "Jhinia",],
                    ["bn_name" => "চিথলিয়া", "jl_no" => "72", "thana_id" => "459", "survey_id" => 5, "name" => "Cithalia",],
                    ["bn_name" => "তেজারকান্দি", "jl_no" => "73", "thana_id" => "459", "survey_id" => 5, "name" => "Tejarkandi",],
                    ["bn_name" => "ইন্দিলপুর", "jl_no" => "74", "thana_id" => "459", "survey_id" => 5, "name" => "Indilpur",],
                    ["bn_name" => "কাড়ারপাড়া", "jl_no" => "75", "thana_id" => "459", "survey_id" => 5, "name" => "Karapara",],
                    ["bn_name" => "অমৃতা", "jl_no" => "76", "thana_id" => "459", "survey_id" => 5, "name" => "Amrita",],
                    ["bn_name" => "গড়জরিপা", "jl_no" => "77", "thana_id" => "459", "survey_id" => 5, "name" => "Garrajaripa",],
                    ["bn_name" => "কুড়িকাহনিয়া", "jl_no" => "78", "thana_id" => "459", "survey_id" => 5, "name" => "Kurikahania",],
                    ["bn_name" => "কুরুয়া", "jl_no" => "79", "thana_id" => "459", "survey_id" => 5, "name" => "Kurua",],
                    ["bn_name" => "চাউলিয়া", "jl_no" => "80", "thana_id" => "459", "survey_id" => 5, "name" => "Chaulia",],
                    ["bn_name" => "গোশাইপুর", "jl_no" => "81", "thana_id" => "459", "survey_id" => 5, "name" => "Goshaipur",],
                    ["bn_name" => "রহমতপুর", "jl_no" => "82", "thana_id" => "459", "survey_id" => 5, "name" => "Rohomotpur",],
                    ["bn_name" => "বালিয়াচন্ডি", "jl_no" => "83", "thana_id" => "459", "survey_id" => 5, "name" => "Baliachondi",],
                    ["bn_name" => "গোপালখিলা", "jl_no" => "85", "thana_id" => "459", "survey_id" => 5, "name" => "Gopalkhila",],
                    ["bn_name" => "শৈলেরপাড়", "jl_no" => "86", "thana_id" => "459", "survey_id" => 5, "name" => "Sailarpar",],
                    ["bn_name" => "দক্ষিণ ঘোনাপাড়া", "jl_no" => "87", "thana_id" => "459", "survey_id" => 5, "name" => "Dokkhingunapara",],
                    ["bn_name" => "বন্দঘোরজান", "jl_no" => "88", "thana_id" => "459", "survey_id" => 5, "name" => "Bandhaghorjan",],
                    ["bn_name" => "চৈতাজানি", "jl_no" => "89", "thana_id" => "459", "survey_id" => 5, "name" => "Chaitajani",],
            // End:: Sreebordi-459 SA-5

            // Start:: Nokla-460 BS-1
                    ["bn_name" => "গনপদ্দী", "jl_no" => "6", "thana_id" => "460", "survey_id" => "1", "name" => "Gonopoddi",],
                    ["bn_name" => "জালালপুর", "jl_no" => "11", "thana_id" => "460", "survey_id" => "1", "name" => "Jalalpur",],
                    ["bn_name" => "গজারিয়া", "jl_no" => "12", "thana_id" => "460", "survey_id" => "1", "name" => "Gojariya",],
                    ["bn_name" => "আদমপুর", "jl_no" => "5", "thana_id" => "460", "survey_id" => "1", "name" => "Adompur",],
                    ["bn_name" => "বারইকান্দি", "jl_no" => "14", "thana_id" => "460", "survey_id" => "1", "name" => "Baroikandi",],
                    ["bn_name" => "পিপড়ীকান্দি", "jl_no" => "4", "thana_id" => "460", "survey_id" => "1", "name" => "Piprikandi",],
                    ["bn_name" => "খারজান", "jl_no" => "4", "thana_id" => "460", "survey_id" => "1", "name" => "Kharjan",],
                    ["bn_name" => "মেদীরপাড়", "jl_no" => "2", "thana_id" => "460", "survey_id" => "1", "name" => "Medirpar",],
                    ["bn_name" => "ভূরদী", "jl_no" => "7", "thana_id" => "460", "survey_id" => "1", "name" => "Vurdi",],
                    ["bn_name" => "বাউসা", "jl_no" => "68", "thana_id" => "460", "survey_id" => "1", "name" => "Bausa",],
                    ["bn_name" => "কবুতরমারী", "jl_no" => "67", "thana_id" => "460", "survey_id" => "1", "name" => "Kobutormari",],
                    ["bn_name" => "মমিনাকান্দা", "jl_no" => "10", "thana_id" => "460", "survey_id" => "1", "name" => "Mominakanda",],
                    ["bn_name" => "চরকৈয়া", "jl_no" => "9", "thana_id" => "460", "survey_id" => "1", "name" => "Corkoiya",],
                    ["bn_name" => "বাজারদি", "jl_no" => "58", "thana_id" => "460", "survey_id" => "1", "name" => "Bajardi",],
                    ["bn_name" => "ফেরূসা", "jl_no" => "16", "thana_id" => "460", "survey_id" => "1", "name" => "Ferusha",],
                    ["bn_name" => "কুর্শাবাদাগৈড়", "jl_no" => "49", "thana_id" => "460", "survey_id" => "1", "name" => "Kurshabadagoir",],
                    ["bn_name" => "নয়াবাড়ী", "jl_no" => "50", "thana_id" => "460", "survey_id" => "1", "name" => "Noyabari",],
                    ["bn_name" => "মাউরা", "jl_no" => "15", "thana_id" => "460", "survey_id" => "1", "name" => "Maura",],
                    ["bn_name" => "বারইকান্দি গড়েরগাঁও", "jl_no" => "17", "thana_id" => "460", "survey_id" => "1", "name" => "Baroikandi Gorergoan",],
                    ["bn_name" => "ছত্রকোনা", "jl_no" => "19", "thana_id" => "460", "survey_id" => "1", "name" => "Chotrokuna",],
                    ["bn_name" => "ধামনা", "jl_no" => "21", "thana_id" => "460", "survey_id" => "1", "name" => "Dhamna",],
                    ["bn_name" => "দনাকুশা", "jl_no" => "22", "thana_id" => "460", "survey_id" => "1", "name" => "Donakusha",],
                    ["bn_name" => "কলাপাড়া", "jl_no" => "57", "thana_id" => "460", "survey_id" => "1", "name" => "Kolapara",],
                    ["bn_name" => "নকলা", "jl_no" => "14", "thana_id" => "460", "survey_id" => "1", "name" => "Nakla",],
                    ["bn_name" => "দরিতেঘরি", "jl_no" => "44", "thana_id" => "460", "survey_id" => "1", "name" => "Doriteghori",],
                    ["bn_name" => "গৌড়দ্বার", "jl_no" => "44", "thana_id" => "460", "survey_id" => "1", "name" => "Gourdwar",],
                    ["bn_name" => "তেঘড়ি", "jl_no" => "45", "thana_id" => "460", "survey_id" => "1", "name" => "Teghori",],
                    ["bn_name" => "ছাতুগাঁও", "jl_no" => "45", "thana_id" => "460", "survey_id" => "1", "name" => "Chatugoan",],
                    ["bn_name" => "রুনিগাঁও", "jl_no" => "46", "thana_id" => "460", "survey_id" => "1", "name" => "Runigoan",],
                    ["bn_name" => "পাইস্কা", "jl_no" => "47", "thana_id" => "460", "survey_id" => "1", "name" => "Paiska",],
                    ["bn_name" => "লাভা", "jl_no" => "48", "thana_id" => "460", "survey_id" => "1", "name" => "Lava",],
                    ["bn_name" => "ধুকুরিয়া", "jl_no" => "18", "thana_id" => "460", "survey_id" => "1", "name" => "Dhukuriya",],
                    ["bn_name" => "সিংগুয়া", "jl_no" => "20", "thana_id" => "460", "survey_id" => "1", "name" => "Singua",],
                    ["bn_name" => "পাঠাকটা", "jl_no" => "80", "thana_id" => "460", "survey_id" => "1", "name" => "Pathakata",],
                    ["bn_name" => "পিপড়ী", "jl_no" => "55", "thana_id" => "460", "survey_id" => "1", "name" => "Pipri",],
                    ["bn_name" => "পলাশকান্দি", "jl_no" => "61", "thana_id" => "460", "survey_id" => "1", "name" => "Polashkandi",],
                    ["bn_name" => "দুধেরচর", "jl_no" => "79", "thana_id" => "460", "survey_id" => "1", "name" => "Dudherchor",],
                    ["bn_name" => "মোজাকান্দা", "jl_no" => "64", "thana_id" => "460", "survey_id" => "1", "name" => "Mujakanda",],
                    ["bn_name" => "চর বসন্তী (2য় খন্ড)", "jl_no" => "84", "thana_id" => "460", "survey_id" => "1", "name" => "Chorbosonti (2nd Part)",],
                    ["bn_name" => "পাচঁকাহনিয়া", "jl_no" => "54", "thana_id" => "460", "survey_id" => "1", "name" => "Panchkahuniya",],
                    ["bn_name" => "বিষ্ণপুর", "jl_no" => "56", "thana_id" => "460", "survey_id" => "1", "name" => "Bishnupur",],
                    ["bn_name" => "বহরদী", "jl_no" => "54", "thana_id" => "460", "survey_id" => "1", "name" => "Bohordi",],
                    ["bn_name" => "খিচা", "jl_no" => "29", "thana_id" => "460", "survey_id" => "1", "name" => "Khica",],
                    ["bn_name" => "উরফা", "jl_no" => "24", "thana_id" => "460", "survey_id" => "1", "name" => "Urfa",],
                    ["bn_name" => "রিহিলা", "jl_no" => "41", "thana_id" => "460", "survey_id" => "1", "name" => "Rihila",],
                    ["bn_name" => "বারমাইশা", "jl_no" => "40", "thana_id" => "460", "survey_id" => "1", "name" => "Baromaisha",],
                    ["bn_name" => "বিমলদি তারাকান্দি", "jl_no" => "25", "thana_id" => "460", "survey_id" => "1", "name" => "Bimoldi Tarakandi",],
                    ["bn_name" => "পিছলাকুড়িঁ", "jl_no" => "24", "thana_id" => "460", "survey_id" => "1", "name" => "Pichlakuri",],
                    ["bn_name" => "রানীশিমুল", "jl_no" => "28", "thana_id" => "460", "survey_id" => "1", "name" => "Ranishimul",],
                    ["bn_name" => "মূজাকান্দা", "jl_no" => "27", "thana_id" => "460", "survey_id" => "1", "name" => "Mujakanda",],
                    ["bn_name" => "শালখা", "jl_no" => "42", "thana_id" => "460", "survey_id" => "1", "name" => "Shalkha",],
                    ["bn_name" => "লয়খা হাসনখিলা", "jl_no" => "26", "thana_id" => "460", "survey_id" => "1", "name" => "Loykha Hashonkhila",],
                    ["bn_name" => "বালিয়াদী", "jl_no" => "65", "thana_id" => "460", "survey_id" => "1", "name" => "Baliyadi",],
                    ["bn_name" => "জানকীপুর", "jl_no" => "66", "thana_id" => "460", "survey_id" => "1", "name" => "Jankipur",],
                    ["bn_name" => "রামপুর", "jl_no" => "70", "thana_id" => "460", "survey_id" => "1", "name" => "Rampur",],
                    ["bn_name" => "চকবড়ইগাছি", "jl_no" => "71", "thana_id" => "460", "survey_id" => "1", "name" => "Cokboroigachi",],
                    ["bn_name" => "চরবেতমারী", "jl_no" => "72", "thana_id" => "460", "survey_id" => "1", "name" => "Corbetmari",],
                    ["bn_name" => "চরবাছুরআলগী", "jl_no" => "74", "thana_id" => "460", "survey_id" => "1", "name" => "Chorbachuralgi",],
                    ["bn_name" => "চরমধুয়া", "jl_no" => "75", "thana_id" => "460", "survey_id" => "1", "name" => "Chormodhuya",],
                    ["bn_name" => "চকরঘুনাথপুর", "jl_no" => "64", "thana_id" => "460", "survey_id" => "1", "name" => "Cokroghunathpur",],
                    ["bn_name" => "চরভবানী", "jl_no" => "77", "thana_id" => "460", "survey_id" => "1", "name" => "Chorvobani",],
                    ["bn_name" => "চর বসন্তী (1ম খন্ড)", "jl_no" => "86", "thana_id" => "460", "survey_id" => "1", "name" => "Chorbosonti (1st Part)",],
                    ["bn_name" => "দেবুয়ারচর", "jl_no" => "88", "thana_id" => "460", "survey_id" => "1", "name" => "Debuyarchor",],
                    ["bn_name" => "দধিয়ারচর", "jl_no" => "76", "thana_id" => "460", "survey_id" => "1", "name" => "Dodiyarchor",],
                    ["bn_name" => "চরভাবনা", "jl_no" => "85", "thana_id" => "460", "survey_id" => "1", "name" => "Chorvabna",],
                    ["bn_name" => "চরঅষ্টধর", "jl_no" => "87", "thana_id" => "460", "survey_id" => "1", "name" => "Choroshtodhor",],
                    ["bn_name" => "নয়াবাড়ী ", "jl_no" => "49", "thana_id" => "460", "survey_id" => "1", "name" => "Noyabari",],
                    ["bn_name" => "মজিদবাড়ী", "jl_no" => "42", "thana_id" => "460", "survey_id" => "1", "name" => "Mojidbari",],
                    ["bn_name" => "বিবিরচর", "jl_no" => "81", "thana_id" => "460", "survey_id" => "1", "name" => "Bibirchor",],
                    ["bn_name" => "সাইলামপুর", "jl_no" => "82", "thana_id" => "460", "survey_id" => "1", "name" => "Sailampur",],
                    ["bn_name" => "চরকামানিরপাড়", "jl_no" => "84", "thana_id" => "460", "survey_id" => "1", "name" => "Chorkamanirpar",],
                    ["bn_name" => "ফুলপুর", "jl_no" => "46", "thana_id" => "460", "survey_id" => "1", "name" => "Phulpur",],
                    ["bn_name" => "রামেরকান্দি", "jl_no" => "47", "thana_id" => "460", "survey_id" => "1", "name" => "Ramerkandi",],
                    ["bn_name" => "চানবাড়ী", "jl_no" => "47", "thana_id" => "460", "survey_id" => "1", "name" => "Chanbari",],
                    ["bn_name" => "বাজিদবাড়ী", "jl_no" => "40", "thana_id" => "460", "survey_id" => "1", "name" => "Bajidbari",],
                    ["bn_name" => "বড়পাগলা", "jl_no" => "44", "thana_id" => "460", "survey_id" => "1", "name" => "Boropagla",],
                    ["bn_name" => "ঝড়াকান্দা", "jl_no" => "44", "thana_id" => "460", "survey_id" => "1", "name" => "Jhorakanda",],
                    ["bn_name" => "টালকী", "jl_no" => "51", "thana_id" => "460", "survey_id" => "1", "name" => "Talki",],
                    ["bn_name" => "সালুয়া", "jl_no" => "52", "thana_id" => "460", "survey_id" => "1", "name" => "Saluya",],
                    ["bn_name" => "পোয়াভাগ", "jl_no" => "41", "thana_id" => "460", "survey_id" => "1", "name" => "Puyavag",],

            // End:: Nokla-460 BS-1

            // Start:: Nokla-460 SA-5
                    ["bn_name" => "বিহারীরপাড়", "jl_no" => "1", "thana_id" => "460", "survey_id" => "5", "name" => "Biharirpar",],
                    ["bn_name" => "বানেশ্বর্দী", "jl_no" => "8", "thana_id" => "460", "survey_id" => "5", "name" => "Banershwordi",],
                    ["bn_name" => "ইশিবপুর", "jl_no" => "59", "thana_id" => "460", "survey_id" => "5", "name" => "Eshibpue",],
                    ["bn_name" => "কায়দা", "jl_no" => "60", "thana_id" => "460", "survey_id" => "5", "name" => "Kaida",],
                    ["bn_name" => "চকজানকিপুর", "jl_no" => "66", "thana_id" => "460", "survey_id" => "5", "name" => "Cokjankipur",],
                    ["bn_name" => "বাছুরআলগা", "jl_no" => "69", "thana_id" => "460", "survey_id" => "5", "name" => "Bachuralga",],
                    ["bn_name" => "চন্দ্রকোনা", "jl_no" => "74", "thana_id" => "460", "survey_id" => "5", "name" => "Chondrakuna",],
                    ["bn_name" => "চরনয়াবাদ", "jl_no" => "78", "thana_id" => "460", "survey_id" => "5", "name" => "Chornoyabad",],
            // End:: Nokla-460 SA-5

            // Start:: Jhenaigati-461 SA-1
                    ["bn_name" => "জড়াকুড়া", "jl_no" => "24", "thana_id" => "461", "survey_id" => "1", "name" => "Jorakura",],
                    ["bn_name" => "পাইকুড়া", "jl_no" => "24", "thana_id" => "461", "survey_id" => "1", "name" => "Paikura",],
                    ["bn_name" => "বালিয়াচন্ডী", "jl_no" => "25", "thana_id" => "461", "survey_id" => "1", "name" => "Baliyachondi",],
                    ["bn_name" => "রামেরকুড়াকোদালজানী", "jl_no" => "47", "thana_id" => "461", "survey_id" => "1", "name" => "Ramerkura Kodaljani",],
                    ["bn_name" => "ঝিনাইগাতী", "jl_no" => "48", "thana_id" => "461", "survey_id" => "1", "name" => "Jhenaigati",],
                    ["bn_name" => "নয়াগাও", "jl_no" => "49", "thana_id" => "461", "survey_id" => "1", "name" => "Noyagaon",],
                    ["bn_name" => "প্রতাবনগর", "jl_no" => "40", "thana_id" => "461", "survey_id" => "1", "name" => "Protabnagar",],
                    ["bn_name" => "কালিনগর", "jl_no" => "41", "thana_id" => "461", "survey_id" => "1", "name" => "Kalinagar",],
                    ["bn_name" => "রামনগর", "jl_no" => "42", "thana_id" => "461", "survey_id" => "1", "name" => "Ramnagar",],
                    ["bn_name" => "বাদেচল্লিশকাহনীয়া", "jl_no" => "44", "thana_id" => "461", "survey_id" => "1", "name" => "Badechollish Kahoniya",],
                    ["bn_name" => "সুরিহারা", "jl_no" => "62", "thana_id" => "461", "survey_id" => "1", "name" => "Surihara",],
                    ["bn_name" => "কোনাগাও", "jl_no" => "65", "thana_id" => "461", "survey_id" => "1", "name" => "Konagaon",],
                    ["bn_name" => "সালধা", "jl_no" => "66", "thana_id" => "461", "survey_id" => "1", "name" => "Saldha",],
                    ["bn_name" => "হাতিবান্দা", "jl_no" => "61", "thana_id" => "461", "survey_id" => "1", "name" => "Hatibandha",],
                    ["bn_name" => "পশ্চিমবৈলতৈল", "jl_no" => "64", "thana_id" => "461", "survey_id" => "1", "name" => "Porcchim Beiltoil",],
                    ["bn_name" => "পুরুষোওমখিলা", "jl_no" => "64", "thana_id" => "461", "survey_id" => "1", "name" => "Poroshuottom Khila",],
                    ["bn_name" => "লয়খা", "jl_no" => "67", "thana_id" => "461", "survey_id" => "1", "name" => "Loykha",],
                    ["bn_name" => "ঘাগরালস্কর", "jl_no" => "68", "thana_id" => "461", "survey_id" => "1", "name" => "Ghagra Loskar",],
                    ["bn_name" => "দুধনই", "jl_no" => "44", "thana_id" => "461", "survey_id" => "1", "name" => "Dodhnoi",],
                    ["bn_name" => "গজারিকুড়া", "jl_no" => "55", "thana_id" => "461", "survey_id" => "1", "name" => "Gojarikura",],
                    ["bn_name" => "হলদীবাটা", "jl_no" => "56", "thana_id" => "461", "survey_id" => "1", "name" => "Holdibata",],
                    ["bn_name" => "গিলাগাছাধরাপানি", "jl_no" => "57", "thana_id" => "461", "survey_id" => "1", "name" => "Gilagacha Dharapani",],
                    ["bn_name" => "গৌরিপুর", "jl_no" => "58", "thana_id" => "461", "survey_id" => "1", "name" => "Gaouripur",],
                    ["bn_name" => "কালাকুড়া", "jl_no" => "59", "thana_id" => "461", "survey_id" => "1", "name" => "Kalakura",],
                    ["bn_name" => "বনগাঁও", "jl_no" => "60", "thana_id" => "461", "survey_id" => "1", "name" => "Bongaon",],
                    ["bn_name" => "ফুলহারী", "jl_no" => "28", "thana_id" => "461", "survey_id" => "1", "name" => "Fulhari",],
                    ["bn_name" => "ভালুকা", "jl_no" => "29", "thana_id" => "461", "survey_id" => "1", "name" => "Valuka",],
                    ["bn_name" => "ডেফলাই", "jl_no" => "40", "thana_id" => "461", "survey_id" => "1", "name" => "Deflai",],
                    ["bn_name" => "রাংটিয়া", "jl_no" => "42", "thana_id" => "461", "survey_id" => "1", "name" => "Rangtiya",],
                    ["bn_name" => "নয়ারাংটিয়া", "jl_no" => "44", "thana_id" => "461", "survey_id" => "1", "name" => "Noya Rangtiya",],
                    ["bn_name" => "শালচূড়া", "jl_no" => "44", "thana_id" => "461", "survey_id" => "1", "name" => "Shalcura",],
                    ["bn_name" => "নুনখোলা", "jl_no" => "45", "thana_id" => "461", "survey_id" => "1", "name" => "Nonkhula",],
                    ["bn_name" => "ডাকাবর", "jl_no" => "46", "thana_id" => "461", "survey_id" => "1", "name" => "Dakabor",],
                    ["bn_name" => "বারুয়ামারী", "jl_no" => "45", "thana_id" => "461", "survey_id" => "1", "name" => "Baruyamari",],
                    ["bn_name" => "ভারুয়া", "jl_no" => "46", "thana_id" => "461", "survey_id" => "1", "name" => "Varuya",],
                    ["bn_name" => "কুশাইকুড়া", "jl_no" => "47", "thana_id" => "461", "survey_id" => "1", "name" => "Kushaikura",],
                    ["bn_name" => "ফাকরাবাদ", "jl_no" => "48", "thana_id" => "461", "survey_id" => "1", "name" => "Fakrabad",],
                    ["bn_name" => "সন্ধ্যাকুড়া", "jl_no" => "49", "thana_id" => "461", "survey_id" => "1", "name" => "Sondhakura",],
                    ["bn_name" => "গোমরা", "jl_no" => "50", "thana_id" => "461", "survey_id" => "1", "name" => "Gomra",],
                    ["bn_name" => "হলদীগ্রাম", "jl_no" => "51", "thana_id" => "461", "survey_id" => "1", "name" => "Holdigram",],
                    ["bn_name" => "পশ্চিমমানিককুড়া", "jl_no" => "52", "thana_id" => "461", "survey_id" => "1", "name" => "Porcchim Manikura",],
                    ["bn_name" => "বাঐবাধা", "jl_no" => "54", "thana_id" => "461", "survey_id" => "1", "name" => "Baoibadha",],
                    ["bn_name" => "জারুলতলা", "jl_no" => "54", "thana_id" => "461", "survey_id" => "1", "name" => "Jarultola",],
                    ["bn_name" => "জোলগাঁও", "jl_no" => "69", "thana_id" => "461", "survey_id" => "1", "name" => "Jholgaon",],
                    ["bn_name" => "ডাকুরপাড়", "jl_no" => "70", "thana_id" => "461", "survey_id" => "1", "name" => "Dakurpar",],
                    ["bn_name" => "চেঙ্গুরিয়া", "jl_no" => "71", "thana_id" => "461", "survey_id" => "1", "name" => "Chenguriya",],
                    ["bn_name" => "বানিয়াপাড়া", "jl_no" => "72", "thana_id" => "461", "survey_id" => "1", "name" => "Baniyapara",],
                    ["bn_name" => "হাসলিবাতিয়া", "jl_no" => "74", "thana_id" => "461", "survey_id" => "1", "name" => "Haslibatiya",],
                    ["bn_name" => "বড়মালঝিকান্দা", "jl_no" => "74", "thana_id" => "461", "survey_id" => "1", "name" => "Boromaljikanda",],
                    ["bn_name" => "রাঙ্গামাটিয়া", "jl_no" => "75", "thana_id" => "461", "survey_id" => "1", "name" => "Rangamatiya",],
                    ["bn_name" => "ধানশাইল", "jl_no" => "15", "thana_id" => "461", "survey_id" => "1", "name" => "Dhansail",],
                    ["bn_name" => "বিলাশপুর", "jl_no" => "16", "thana_id" => "461", "survey_id" => "1", "name" => "Bilashpur",],
                    ["bn_name" => "কান্দুলী", "jl_no" => "17", "thana_id" => "461", "survey_id" => "1", "name" => "Kanduli",],
                    ["bn_name" => "ভবানীখিলা", "jl_no" => "18", "thana_id" => "461", "survey_id" => "1", "name" => "Vobanikhila",],
                    ["bn_name" => "কুচনীপাড়া", "jl_no" => "19", "thana_id" => "461", "survey_id" => "1", "name" => "Kuchnipara",],
                    ["bn_name" => "নিজামখিলা", "jl_no" => "20", "thana_id" => "461", "survey_id" => "1", "name" => "Nizamkhila",],
                    ["bn_name" => "ছোট মালঝিকান্দা", "jl_no" => "21", "thana_id" => "461", "survey_id" => "1", "name" => "Soto Maljikanda",],
                    ["bn_name" => "জগৎপুর", "jl_no" => "22", "thana_id" => "461", "survey_id" => "1", "name" => "Jogothpur",],
                    ["bn_name" => "দারিয়ারপাড়", "jl_no" => "26", "thana_id" => "461", "survey_id" => "1", "name" => "Dariyarpar",],
                    ["bn_name" => "চাপাজোড়া", "jl_no" => "27", "thana_id" => "461", "survey_id" => "1", "name" => "Chapajura",],
                    ["bn_name" => "জোকাকুড়া", "jl_no" => "2", "thana_id" => "461", "survey_id" => "1", "name" => "Jukakura",],
                    ["bn_name" => "কাংশা", "jl_no" => "4", "thana_id" => "461", "survey_id" => "1", "name" => "Kangsha",],
                    ["bn_name" => "বিঞ্চুপুর", "jl_no" => "4", "thana_id" => "461", "survey_id" => "1", "name" => "Bishnupur",],
                    ["bn_name" => "নাচনমহরী", "jl_no" => "5", "thana_id" => "461", "survey_id" => "1", "name" => "Nachonmuhuri",],
                    ["bn_name" => "আয়নাপুর", "jl_no" => "6", "thana_id" => "461", "survey_id" => "1", "name" => "Aynapur",],
                    ["bn_name" => "কারাগাঁও", "jl_no" => "7", "thana_id" => "461", "survey_id" => "1", "name" => "Karagaon",],
                    ["bn_name" => "দুপুরিয়া", "jl_no" => "8", "thana_id" => "461", "survey_id" => "1", "name" => "Dupuriya",],
                    ["bn_name" => "পানবর", "jl_no" => "9", "thana_id" => "461", "survey_id" => "1", "name" => "Panbor",],
                    ["bn_name" => "গরুচরণদুধনৈ", "jl_no" => "10", "thana_id" => "461", "survey_id" => "1", "name" => "GuruCharon Dudhnoi",],
                    ["bn_name" => "গজনী", "jl_no" => "11", "thana_id" => "461", "survey_id" => "1", "name" => "Gazni",],
                    ["bn_name" => "হালচাটি", "jl_no" => "12", "thana_id" => "461", "survey_id" => "1", "name" => "Halchati",],
                    ["bn_name" => "গান্ধিগাঁও", "jl_no" => "14", "thana_id" => "461", "survey_id" => "1", "name" => "Gandhigaon",],
                    ["bn_name" => "বাকাকুড়া", "jl_no" => "14", "thana_id" => "461", "survey_id" => "1", "name" => "Bakakura",],
                    ["bn_name" => "নওকুচি", "jl_no" => "41", "thana_id" => "461", "survey_id" => "1", "name" => "Naoukuchi",],
            // End:: Jhenaigati-461 SA-1

            // Start:: Jhenaigati-461 SA-5
                    ["bn_name" => "তাওয়াকুচা", "jl_no" => "1", "thana_id" => "461", "survey_id" => "5", "name" => "Taoyakuca",],
            // End:: Jhenaigati-461 SA-5
        ];
        Mouza::insert($data);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    }
}
